type Query {
  dexAmmProtocols(
    skip: Int = 0
    first: Int = 100
    orderBy: DexAmmProtocol_orderBy
    orderDirection: OrderDirection
    where: DexAmmProtocol_filter

    """
    The block at which the query should be executed. Can either be a `{ hash: Bytes }` value containing a block hash, a `{ number: Int }` containing the block number, or a `{ number_gte: Int }` containing the minimum block number. In the case of `number_gte`, the query will be executed on the latest block only if the subgraph has progressed to or past the minimum block number. Defaults to the latest block when omitted.
    """
    block: Block_height

    """
    Set to `allow` to receive data even if the subgraph has skipped over errors while syncing.
    """
    subgraphError: _SubgraphErrorPolicy_! = deny
  ): [DexAmmProtocol!]!

  """Access to subgraph metadata"""
  _meta(block: Block_height): _Meta_
}

input Block_height {
  hash: Bytes
  number: Int
  number_gte: Int
}

scalar Bytes

"""The type for the top-level _meta field"""
type _Meta_ {
  "Information about a specific subgraph block. The hash of the block\nwill be null if the _meta field has a block constraint that asks for\na block number. It will be filled if the _meta field has no block constraint\nand therefore asks for the latest  block\n"
  block: _Block_!

  """The deployment ID"""
  deployment: String!

  """If `true`, the subgraph encountered indexing errors at some past block"""
  hasIndexingErrors: Boolean!
}

type _Block_ {
  """The hash of the block"""
  hash: Bytes

  """The block number"""
  number: Int!

  """Integer representation of the timestamp stored in blocks for the chain"""
  timestamp: Int
}

enum _SubgraphErrorPolicy_ {
  """Data will be returned even if the subgraph has indexing errors"""
  allow

  """
  If the subgraph has indexing errors, data will be omitted. The default.
  """
  deny
}

input DexAmmProtocol_filter {
  id: Bytes
}

"""Defines the order direction, either ascending or descending"""
enum OrderDirection {
  asc
  desc
}

enum DexAmmProtocol_orderBy {
  id
  name
  slug
  schemaVersion
  subgraphVersion
  methodologyVersion
  network
  type
  totalValueLockedUSD
  totalLiquidityUSD
  activeLiquidityUSD
  uncollectedProtocolSideValueUSD
  uncollectedSupplySideValueUSD
  protocolControlledValueUSD
  cumulativeVolumeUSD
  cumulativeSupplySideRevenueUSD
  cumulativeProtocolSideRevenueUSD
  cumulativeTotalRevenueUSD
  cumulativeUniqueUsers
  cumulativeUniqueLPs
  cumulativeUniqueTraders
  totalPoolCount
  openPositionCount
  cumulativePositionCount
  lastSnapshotDayID
  lastUpdateTimestamp
  lastUpdateBlockNumber
  dailyUsageMetrics
  hourlyUsageMetrics
  financialMetrics
  pools
  _regenesis
}

type DexAmmProtocol implements Protocol {
  """ Smart contract address of the protocol's main contract (Factory, Registry, etc)
  """
  id: Bytes!

  """ Name of the protocol, including version. e.g. Uniswap v3 """
  name: String!

  """ Version of the subgraph schema, in SemVer format (e.g. 1.0.0) """
  schemaVersion: String!

  """ Version of the subgraph implementation, in SemVer format (e.g. 1.0.0)
  """
  subgraphVersion: String!

  """ Version of the methodology used to compute metrics, loosely based on SemVer format (e.g. 1.0.0)
  """
  methodologyVersion: String!

  """ The blockchain network this subgraph is indexing on """
  network: Network!

  """ Current TVL (Total Value Locked) of the entire protocol """
  totalValueLockedUSD: BigDecimal!

  """ All historical volume in USD """
  cumulativeVolumeUSD: BigDecimal!

  """ Revenue claimed by suppliers to the protocol. LPs on DEXs (e.g. 0.25% of the swap fee in Sushiswap). Depositors on Lending Protocols. NFT sellers on OpenSea.
  """
  cumulativeSupplySideRevenueUSD: BigDecimal!

  """ Gross revenue for the protocol (revenue claimed by protocol). Examples: AMM protocol fee (Sushi’s 0.05%). OpenSea 10% sell fee.
  """
  cumulativeProtocolSideRevenueUSD: BigDecimal!

  """ All revenue generated by the protocol. e.g. 0.30% of swap fee in Sushiswap, all yield generated by Yearn.
  """
  cumulativeTotalRevenueUSD: BigDecimal!

  """ Total number of pools """
  totalPoolCount: Int!
}

interface Protocol {
  """ Smart contract address of the protocol's main contract (Factory, Registry, etc)
  """
  id: Bytes!

  """ Name of the protocol, including version. e.g. Uniswap v3 """
  name: String!

  """ Version of the subgraph schema, in SemVer format (e.g. 1.0.0) """
  schemaVersion: String!

  """ Version of the subgraph implementation, in SemVer format (e.g. 1.0.0)
  """
  subgraphVersion: String!

  """ Version of the methodology used to compute metrics, loosely based on SemVer format (e.g. 1.0.0)
  """
  methodologyVersion: String!

  """ The blockchain network this subgraph is indexing on """
  network: Network!

  """ Current TVL (Total Value Locked) of the entire protocol """
  totalValueLockedUSD: BigDecimal!

  """ Revenue claimed by suppliers to the protocol. LPs on DEXs (e.g. 0.25% of the swap fee in Sushiswap). Depositors on Lending Protocols. NFT sellers on OpenSea.
  """
  cumulativeSupplySideRevenueUSD: BigDecimal!

  """ Gross revenue for the protocol (revenue claimed by protocol). Examples: AMM protocol fee (Sushi’s 0.05%). OpenSea 10% sell fee.
  """
  cumulativeProtocolSideRevenueUSD: BigDecimal!

  """ All revenue generated by the protocol. e.g. 0.30% of swap fee in Sushiswap, all yield generated by Yearn.
  """
  cumulativeTotalRevenueUSD: BigDecimal!

  """ Total number of pools """
  totalPoolCount: Int!
}

scalar BigDecimal

enum Network {
  ARBITRUM_ONE
  ARWEAVE_MAINNET
  AURORA
  AVALANCHE
  BASE
  BOBA
  BSC
  CELO
  COSMOS
  CRONOS
  MAINNET
  FANTOM
  FUSE
  HARMONY
  JUNO
  MOONBEAM
  MOONRIVER
  NEAR_MAINNET
  OPTIMISM
  OSMOSIS
  MATIC
  XDAI
}
