packages:
  - .

verifyDepsBeforeRun: false

overrides:
  '@napi-rs/wasm-runtime': 1.1.5
  cookie: 0.7.2

peerDependencyRules:
  allowedVersions:
    'openapi-typescript>typescript': ^5 || ^6

supportedArchitectures:
  cpu:
    - current
    - wasm32

allowBuilds:
  '@journeyapps/wa-sqlite': true
  es5-ext: false
  esbuild: true

patchedDependencies:
  '@tanstack/db-sqlite-persistence-core@0.1.11': patches/@tanstack__db-sqlite-persistence-core@0.1.11.patch
