import type { NavigationItem } from '$/routes/NavigationItem.ts'

export const useNavigationItems = () => {
	const navigationItems = $derived([
		{
			id: 'local-dashboards',
			title: 'Dashboards',
			href: '/~/dashboards',
			icon: '📊',
			defaultIsOpen: true,
			children: [],
		},
		{
			id: 'local-accounts',
			title: 'Accounts',
			href: '/~/accounts',
			icon: '🔑',
			defaultIsOpen: true,
			children: [
				{
					id: 'local-connections',
					title: 'Connections',
					href: '/~/accounts/connections',
					icon: '🔌',
				},
				{
					id: 'local-watched-accounts',
					title: 'Watched accounts',
					href: '/~/accounts/watched-accounts',
					icon: '👛',
				},
				{
					id: 'local-balances',
					title: 'Balances',
					href: '/~/accounts/balances',
					icon: '🪙',
				},
				{
					id: 'local-allowances',
					title: 'Allowances',
					href: '/~/accounts/allowances',
					icon: '🔓',
				},
				{
					id: 'local-positions',
					title: 'Positions',
					href: '/~/accounts/positions',
					icon: '📈',
				},
				{
					id: 'local-transactions',
					title: 'Transactions',
					href: '/~/accounts/transactions',
					icon: '🧾',
				},
			],
		},
		{
			id: 'local-sessions',
			title: 'Sessions',
			href: '/~/sessions',
			icon: '🧪',
			defaultIsOpen: true,
			children: [],
		},
		{
			id: 'explore',
			title: 'Explore',
			href: '/explore',
			icon: '🧭',
			defaultIsOpen: true,
			children: [
				{
					id: 'explore-networks',
					title: 'Networks',
					href: '/networks',
					icon: '🌐',
					defaultIsOpen: true,
					children: [
						{
							id: 'explore-networks-bitcoin',
							title: 'Bitcoin',
							href: '/network/bitcoin',
							icon: '₿',
						},
						{
							id: 'explore-networks-ethereum',
							title: 'Ethereum',
							href: '/network/ethereum',
							icon: 'Ξ',
						},
					],
				},
				{
					id: 'explore-contracts',
					title: 'Contracts',
					href: '/contracts',
					icon: '📜',
					defaultIsOpen: true,
					children: [],
				},
				{
					id: 'explore-ens',
					title: 'ENS',
					href: '/ens',
					icon: '🪪',
				},
				{
					id: 'explore-services',
					title: 'Services',
					href: '/services',
					icon: '⚙️',
				},
				{
					id: 'explore-ipfs',
					title: 'IPFS',
					href: '/ipfs',
					icon: '🗂️',
				},
				{
					id: 'explore-swarm',
					title: 'Swarm',
					href: '/swarm',
					icon: '🐝',
				},
				{
					id: 'explore-proposals',
					title: 'Proposals',
					href: '/proposals',
					icon: '🗳️',
					defaultIsOpen: true,
					children: [
						{
							id: 'explore-proposals-ethereum',
							title: 'Ethereum',
							href: '/proposals/ethereum',
							icon: '⬨',
						},
						{
							id: 'explore-proposals-ens',
							title: 'ENS',
							href: '/proposals/ens',
							icon: '🪪',
						},
						{
							id: 'explore-proposals-chain-agnostic',
							title: 'Chain Agnostic',
							href: '/proposals/chain-agnostic',
							icon: '📎',
						},
					],
				},
				{
					id: 'explore-upgrades',
					title: 'Upgrades',
					href: '/upgrades',
					icon: '🔀',
					defaultIsOpen: true,
					children: [],
				},
				{
					id: 'explore-evm',
					title: 'EVM',
					href: '/evm',
					icon: '🛠️',
					defaultIsOpen: false,
					children: [
						{
							id: 'explore-evm-calldata',
							title: 'Calldata',
							href: '/evm/calldata',
							icon: '📦',
						},
						{
							id: 'explore-evm-calldata-decoder',
							title: 'Calldata decoder',
							href: '/evm/calldata-decoder',
							icon: '🔍',
						},
						{
							id: 'explore-evm-selectors',
							title: 'Selectors',
							href: '/evm/selectors',
							icon: '🎯',
							children: [],
						},
						{
							id: 'explore-evm-topics',
							title: 'Topics',
							href: '/evm/topics',
							icon: '📑',
							children: [],
						},
						{
							id: 'explore-evm-errors',
							title: 'Errors',
							href: '/evm/errors',
							icon: '⚠️',
							children: [],
						},
					],
				},
			],
		},
		{
			id: 'assets',
			title: 'Assets',
			href: '/assets',
			icon: '💼',
			defaultIsOpen: true,
			children: [
				{
					id: 'assets-coins',
					title: 'Coins',
					href: '/coins',
					icon: '🪙',
					defaultIsOpen: true,
					children: [
						{
							id: 'assets-coins-quotes',
							title: 'Spot quotes',
							href: '/coins/prices',
							icon: '💹',
						},
						{
							id: 'assets-coins-candles',
							title: 'Candles',
							href: '/coins/candles',
							icon: '📊',
						},
					],
				},
				{
					id: 'assets-markets',
					title: 'Markets',
					href: '/markets',
					icon: '🔀',
				},
				{
					id: 'assets-market-venues',
					title: 'Market venues',
					href: '/market-venues',
					icon: '🏛️',
				},
				{
					id: 'assets-currencies',
					title: 'Currencies',
					href: '/currencies',
					icon: '💱',
				},
				{
					id: 'assets-pools',
					title: 'Pools',
					href: '/pools',
					icon: '🌊',
				},
				{
					id: 'assets-vaults',
					title: 'Vaults',
					href: '/vaults',
					icon: '📈',
				},
				{
					id: 'assets-leverage',
					title: 'Leverage',
					href: '/leverage',
					icon: '⚖️',
				},
				{
					id: 'assets-channels',
					title: 'Channels',
					href: '/channels',
					icon: '↔️',
				},
			],
		},
		{
			id: 'agents',
			title: 'Agents',
			href: '/~/agents',
			icon: '🤖',
			defaultIsOpen: true,
			children: [
				{
					id: 'agents-conversations',
					title: 'Conversations',
					href: '/~/agents/conversations',
					icon: '🗨️',
				},
			],
		},
		{
			id: 'social',
			title: 'Social',
			href: '/social',
			icon: '👥',
			defaultIsOpen: true,
			children: [
				{
					id: 'social-activitypub',
					title: 'ActivityPub',
					href: '/activitypub',
					icon: '🐘',
					children: [
						{
							id: 'social-activitypub-actors',
							title: 'Actors',
							href: '/activitypub/actors',
							icon: '👤',
							children: [],
						},
						{
							id: 'social-activitypub-notes',
							title: 'Notes',
							href: '/activitypub/notes',
							icon: '📝',
							children: [],
						},
					],
				},
				{
					id: 'social-atproto',
					title: 'AT Protocol',
					href: '/atproto',
					icon: '🦋',
					children: [
						{
							id: 'social-atproto-actors',
							title: 'Actors',
							href: '/atproto/actors',
							icon: '👤',
							children: [],
						},
						{
							id: 'social-atproto-posts',
							title: 'Posts',
							href: '/atproto/posts',
							icon: '📝',
							children: [],
						},
					],
				},
				{
					id: 'social-farcaster',
					title: 'Farcaster',
					href: '/farcaster',
					icon: '🏛️',
					defaultIsOpen: false,
					children: [
						{
							id: 'social-farcaster-accounts',
							title: 'Accounts',
							href: '/farcaster/accounts',
							icon: '👤',
							children: [],
						},
						{
							id: 'social-farcaster-feed',
							title: 'Feed',
							href: '/farcaster/feed',
							icon: '📰',
							children: [
								{
									id: 'social-farcaster-feed-trending',
									title: 'Trending',
									href: '/farcaster/feed/trending',
									icon: '🔥',
									children: [],
								},
							],
						},
						{
							id: 'social-farcaster-channels',
							title: 'Channels',
							href: '/farcaster/channels',
							icon: '📺',
						},
						{
							id: 'social-farcaster-users',
							title: 'Users',
							href: '/farcaster/users',
							icon: '👥',
						},
					],
				},
				{
					id: 'social-lens',
					title: 'Lens',
					href: '/lens',
					icon: '☘️',
					children: [
						{
							id: 'social-lens-accounts',
							title: 'Profiles',
							href: '/lens/accounts',
							icon: '👤',
							children: [],
						},
						{
							id: 'social-lens-posts',
							title: 'Publications',
							href: '/lens/posts',
							icon: '📝',
							children: [],
						},
					],
				},
				{
					id: 'social-nostr',
					title: 'Nostr',
					href: '/nostr',
					icon: '⚡',
					children: [
						{
							id: 'social-nostr-relays',
							title: 'Relays',
							href: '/nostr/relays',
							icon: '📡',
							children: [],
						},
						{
							id: 'social-nostr-profiles',
							title: 'Profiles',
							href: '/nostr/profiles',
							icon: '👤',
							children: [],
						},
						{
							id: 'social-nostr-notes',
							title: 'Notes',
							href: '/nostr/notes',
							icon: '📝',
							children: [],
						},
						{
							id: 'social-nostr-reposts',
							title: 'Reposts',
							href: '/nostr/reposts',
							icon: '🔁',
							children: [],
						},
						{
							id: 'social-nostr-articles',
							title: 'Articles',
							href: '/nostr/articles',
							icon: '📄',
							children: [],
						},
					],
				},
				{
					id: 'social-reddit',
					title: 'Reddit',
					href: '/reddit',
					icon: '🤖',
					children: [
						{
							id: 'social-reddit-subreddits',
							title: 'Subreddits',
							href: '/reddit/subreddits',
							icon: '📋',
							children: [],
						},
						{
							id: 'social-reddit-links',
							title: 'Submissions',
							href: '/reddit/links',
							icon: '📝',
							children: [],
						},
					],
				},
				{
					id: 'social-rss',
					title: 'RSS',
					href: '/rss',
					icon: '📰',
					children: [
						{
							id: 'social-rss-feeds',
							title: 'Feeds',
							href: '/rss/feeds',
							icon: '📡',
							children: [],
						},
						{
							id: 'social-rss-items',
							title: 'Items',
							href: '/rss/items',
							icon: '📝',
							children: [],
						},
					],
				},
				{
					id: 'social-x',
					title: 'X',
					href: '/x',
					icon: '𝕏',
					children: [
						{
							id: 'social-x-users',
							title: 'Users',
							href: '/x/users',
							icon: '👥',
							children: [],
						},
						{
							id: 'social-x-posts',
							title: 'Posts',
							href: '/x/posts',
							icon: '📝',
							children: [],
						},
					],
				},
				{
					id: 'social-youtube',
					title: 'YouTube',
					href: '/youtube',
					icon: '▶️',
					children: [
						{
							id: 'social-youtube-channels',
							title: 'Channels',
							href: '/youtube/channels',
							icon: '📺',
							children: [],
						},
						{
							id: 'social-youtube-videos',
							title: 'Videos',
							href: '/youtube/videos',
							icon: '🎬',
							children: [],
						},
						{
							id: 'social-youtube-playlists',
							title: 'Playlists',
							href: '/youtube/playlists',
							icon: '📋',
							children: [],
						},
					],
				},
				{
					id: 'social-xmtp',
					title: 'XMTP',
					href: '/xmtp',
					icon: '💬',
					defaultIsOpen: false,
					children: [
						{
							id: 'social-xmtp-accounts',
							title: 'Accounts',
							href: '/xmtp/accounts',
							icon: '👤',
							children: [],
						},
						{
							id: 'social-xmtp-conversations',
							title: 'Conversations',
							href: '/xmtp/conversations',
							icon: '💬',
							children: [],
						},
					],
				},
			],
		},
		{
			id: 'local-multiplayer',
			title: 'Multiplayer',
			href: '/~/multiplayer',
			icon: '🤝',
			defaultIsOpen: true,
			children: [
				{
					id: 'local-multiplayer-rooms',
					title: 'Rooms',
					href: '/~/multiplayer/rooms',
					icon: '🏘️',
					children: [],
				},
				{
					id: 'local-multiplayer-contacts',
					title: 'Contacts',
					href: '/~/multiplayer/contacts',
					icon: '📇',
					children: [],
				},
			],
		},
		{
			id: 'local-manage',
			title: 'Manage',
			href: '/~/manage',
			icon: '⚙️',
			defaultIsOpen: true,
			children: [
				{
					id: 'local-manage-profiles',
					title: 'Profiles',
					href: '/~/manage/profiles',
					icon: '👤',
				},
				{
					id: 'local-manage-sources',
					title: 'Sources',
					href: '/~/manage/sources',
					icon: '📡',
				},
				{
					id: 'local-manage-data',
					title: 'Data',
					href: '/~/manage/data',
					icon: '🗄️',
				},
			],
		},
	] satisfies NavigationItem[])

	return {
		get navigationItems() {
			return navigationItems
		},
	}
}
