// Generated from APP.ts.

import type { NavigationItem } from '$/routes/NavigationItem.ts'

export default [
	{
		id: 'local-dashboards',
		title: 'Dashboards',
		href: '/~/dashboards',
		icon: '📊',
		defaultIsOpen: true,
	},
	{
		id: 'local-accounts',
		title: 'Accounts',
		href: '/~/accounts',
		icon: '🔑',
		defaultIsOpen: true,
		children: [
			{
				id: 'local-balances',
				title: 'Balances',
				href: '/~/accounts/balances',
				icon: '🪙',
			},
			{
				id: 'local-allowances',
				title: 'Allowances',
				href: '/~/accounts/allowances',
				icon: '🔓',
			},
			{
				id: 'local-transactions',
				title: 'Transactions',
				href: '/~/accounts/transactions',
				icon: '🧾',
			},
		],
	},
	{
		id: 'local-sessions',
		title: 'Sessions',
		href: '/~/sessions',
		icon: '🧪',
		defaultIsOpen: true,
	},
	{
		id: 'local-wallets',
		title: 'Wallets',
		href: '/~/wallets',
		icon: '👛',
		defaultIsOpen: true,
		children: [
			{
				id: 'local-wallet-connections',
				title: 'Connections',
				href: '/~/wallets/connections',
				icon: '🔌',
			},
			{
				id: 'local-wallet-requests',
				title: 'Requests',
				href: '/~/wallets/requests',
				icon: '📝',
			},
		],
	},
	{
		id: 'explore',
		title: 'Explore',
		href: '/explore',
		icon: '🧭',
		defaultIsOpen: true,
		children: [
			{
				id: 'explore-networks',
				title: 'Networks',
				href: '/networks',
				icon: '🌐',
				defaultIsOpen: true,
				children: [
					{
						id: 'explore-networks-bitcoin',
						title: 'Bitcoin',
						href: '/network/bitcoin',
						icon: '₿',
					},
					{
						id: 'explore-networks-ethereum',
						title: 'Ethereum',
						href: '/network/eip155:1',
						icon: 'Ξ',
					},
				],
			},
			{
				id: 'explore-contracts',
				title: 'Contracts',
				href: '/contracts',
				icon: '📜',
				defaultIsOpen: true,
			},
			{
				id: 'explore-ens',
				title: 'ENS',
				href: '/ens',
				icon: '🪪',
			},
			{
				id: 'explore-services',
				title: 'Services',
				href: '/services',
				icon: '⚙️',
			},
			{
				id: 'explore-ipfs',
				title: 'IPFS',
				href: '/ipfs',
				icon: '🗂️',
			},
			{
				id: 'explore-swarm',
				title: 'Swarm',
				href: '/swarm',
				icon: '🐝',
			},
			{
				id: 'explore-proposals',
				title: 'Proposals',
				href: '/proposals',
				icon: '🗳️',
				defaultIsOpen: true,
				children: [
					{
						id: 'explore-proposals-ethereum',
						title: 'Ethereum',
						href: '/proposals/ethereum',
						icon: '⬨',
					},
					{
						id: 'explore-proposals-ens',
						title: 'ENS',
						href: '/proposals/ens',
						icon: '🪪',
					},
					{
						id: 'explore-proposals-chain-agnostic',
						title: 'Chain Agnostic',
						href: '/proposals/chain-agnostic',
						icon: '📎',
					},
				],
			},
			{
				id: 'explore-upgrades',
				title: 'Upgrades',
				href: '/upgrades',
				icon: '🔀',
				defaultIsOpen: true,
			},
			{
				id: 'explore-evm',
				title: 'EVM',
				href: '/evm',
				icon: '🛠️',
				children: [
					{
						id: 'explore-evm-calldata',
						title: 'Calldata',
						href: '/evm/calldata-decoder',
						icon: '📦',
					},
					{
						id: 'explore-evm-calldata-decoder',
						title: 'Calldata decoder',
						href: '/evm/calldata-decoder',
						icon: '🔍',
					},
					{
						id: 'explore-evm-selectors',
						title: 'Selectors',
						href: '/evm/selectors',
						icon: '🎯',
					},
					{
						id: 'explore-evm-topics',
						title: 'Topics',
						href: '/evm/topics',
						icon: '📑',
					},
					{
						id: 'explore-evm-errors',
						title: 'Errors',
						href: '/evm/errors',
						icon: '⚠️',
					},
				],
			},
			{
				id: 'assets',
				title: 'Assets',
				href: '/assets',
				icon: '💼',
				defaultIsOpen: true,
				children: [
					{
						id: 'assets-coins',
						title: 'Coins',
						href: '/coins',
						icon: '🪙',
						defaultIsOpen: true,
						children: [
							{
								id: 'assets-coins-quotes',
								title: 'Spot quotes',
								href: '/coins/prices',
								icon: '💹',
							},
							{
								id: 'assets-coins-candles',
								title: 'Candles',
								href: '/coins/candles',
								icon: '📊',
							},
						],
					},
					{
						id: 'assets-markets',
						title: 'Markets',
						href: '/markets',
						icon: '🔀',
					},
					{
						id: 'assets-market-venues',
						title: 'Market venues',
						href: '/market-venues',
						icon: '🏛️',
					},
					{
						id: 'assets-currencies',
						title: 'Currencies',
						href: '/currencies',
						icon: '💱',
					},
					{
						id: 'assets-pools',
						title: 'Pools',
						href: '/pools',
						icon: '🌊',
					},
					{
						id: 'assets-channels',
						title: 'Channels',
						href: '/channels',
						icon: '↔️',
					},
				],
			},
			{
				id: 'agents',
				title: 'Agents',
				href: '/~/agents',
				icon: '🤖',
				defaultIsOpen: true,
				children: [
					{
						id: 'agents-conversations',
						title: 'Conversations',
						href: '/~/agents/conversations',
						icon: '🗨️',
					},
				],
			},
			{
				id: 'social',
				title: 'Social',
				href: '/social',
				icon: '👥',
				defaultIsOpen: true,
				children: [
					{
						id: 'social-activitypub',
						title: 'ActivityPub',
						href: '/activitypub',
						icon: '🐘',
						children: [
							{
								id: 'social-activitypub-actors',
								title: 'Actors',
								href: '/activitypub/actors',
								icon: '👤',
							},
							{
								id: 'social-activitypub-notes',
								title: 'Notes',
								href: '/activitypub/notes',
								icon: '📝',
							},
						],
					},
					{
						id: 'social-atproto',
						title: 'AT Protocol',
						href: '/atproto',
						icon: '🦋',
						children: [
							{
								id: 'social-atproto-actors',
								title: 'Actors',
								href: '/atproto/actors',
								icon: '👤',
							},
							{
								id: 'social-atproto-posts',
								title: 'Posts',
								href: '/atproto/posts',
								icon: '📝',
							},
						],
					},
					{
						id: 'social-farcaster',
						title: 'Farcaster',
						href: '/farcaster',
						icon: '🏛️',
						children: [
							{
								id: 'social-farcaster-accounts',
								title: 'Accounts',
								href: '/farcaster/accounts',
								icon: '👤',
							},
							{
								id: 'social-farcaster-feed',
								title: 'Feed',
								href: '/farcaster/feed',
								icon: '📰',
								children: [
									{
										id: 'social-farcaster-feed-trending',
										title: 'Trending',
										href: '/farcaster/feed/trending',
										icon: '🔥',
									},
								],
							},
							{
								id: 'social-farcaster-channels',
								title: 'Channels',
								href: '/farcaster/channels',
								icon: '📺',
							},
							{
								id: 'social-farcaster-users',
								title: 'Users',
								href: '/farcaster/users',
								icon: '👥',
							},
						],
					},
					{
						id: 'social-lens',
						title: 'Lens',
						href: '/lens',
						icon: '☘️',
						children: [
							{
								id: 'social-lens-accounts',
								title: 'Profiles',
								href: '/lens/observations/accounts',
								icon: '👤',
							},
							{
								id: 'social-lens-feeds',
								title: 'Feeds',
								href: '/lens/feed',
								icon: '📰',
							},
							{
								id: 'social-lens-namespaces',
								title: 'Namespaces',
								href: '/lens/namespace',
								icon: '🏷️',
							},
							{
								id: 'social-lens-posts',
								title: 'Publications',
								href: '/lens/observations/posts',
								icon: '📝',
							},
						],
					},
					{
						id: 'social-nostr',
						title: 'Nostr',
						href: '/nostr',
						icon: '⚡',
						children: [
							{
								id: 'social-nostr-relays',
								title: 'Relays',
								href: '/nostr/relays',
								icon: '📡',
							},
							{
								id: 'social-nostr-profiles',
								title: 'Profiles',
								href: '/nostr/profiles',
								icon: '👤',
							},
							{
								id: 'social-nostr-notes',
								title: 'Notes',
								href: '/nostr/notes',
								icon: '📝',
							},
							{
								id: 'social-nostr-reposts',
								title: 'Reposts',
								href: '/nostr/reposts',
								icon: '🔁',
							},
							{
								id: 'social-nostr-articles',
								title: 'Articles',
								href: '/nostr/articles',
								icon: '📄',
							},
						],
					},
					{
						id: 'social-reddit',
						title: 'Reddit',
						href: '/reddit',
						icon: '🤖',
						children: [
							{
								id: 'social-reddit-subreddits',
								title: 'Subreddits',
								href: '/reddit/subreddits',
								icon: '📋',
							},
							{
								id: 'social-reddit-links',
								title: 'Submissions',
								href: '/reddit/links',
								icon: '📝',
							},
						],
					},
					{
						id: 'governance-snapshot',
						title: 'Snapshot',
						href: '/snapshot/spaces',
						icon: '🗳️',
					},
					{
						id: 'governance-tally',
						title: 'Tally',
						href: '/tally',
						icon: '⚖️',
					},
					{
						id: 'social-rss',
						title: 'RSS',
						href: '/rss',
						icon: '📰',
						children: [
							{
								id: 'social-rss-feeds',
								title: 'Feeds',
								href: '/rss/feeds',
								icon: '📡',
							},
						],
					},
					{
						id: 'social-x',
						title: 'X',
						href: '/x',
						icon: '𝕏',
						children: [
							{
								id: 'social-x-users',
								title: 'Users',
								href: '/x/users',
								icon: '👥',
							},
							{
								id: 'social-x-posts',
								title: 'Posts',
								href: '/x/posts',
								icon: '📝',
							},
						],
					},
					{
						id: 'social-youtube',
						title: 'YouTube',
						href: '/youtube',
						icon: '▶️',
						children: [
							{
								id: 'social-youtube-channels',
								title: 'Channels',
								href: '/youtube/channels',
								icon: '📺',
							},
							{
								id: 'social-youtube-videos',
								title: 'Videos',
								href: '/youtube/videos',
								icon: '🎬',
							},
							{
								id: 'social-youtube-playlists',
								title: 'Playlists',
								href: '/youtube/playlists',
								icon: '📋',
							},
						],
					},
					{
						id: 'social-xmtp',
						title: 'XMTP',
						href: '/xmtp',
						icon: '💬',
						children: [
							{
								id: 'social-xmtp-accounts',
								title: 'Accounts',
								href: '/xmtp/accounts',
								icon: '👤',
							},
							{
								id: 'social-xmtp-conversations',
								title: 'Conversations',
								href: '/xmtp/conversations',
								icon: '💬',
							},
						],
					},
				],
			},
		],
	},
	{
		id: 'local-multiplayer',
		title: 'Multiplayer',
		href: '/~/multiplayer',
		icon: '🤝',
		defaultIsOpen: true,
		children: [
			{
				id: 'local-multiplayer-rooms',
				title: 'Rooms',
				href: '/~/multiplayer/rooms',
				icon: '🏘️',
			},
			{
				id: 'local-multiplayer-contacts',
				title: 'Contacts',
				href: '/~/multiplayer/contacts',
				icon: '📇',
			},
		],
	},
	{
		id: 'local-manage',
		title: 'Manage',
		href: '/~/manage',
		icon: '⚙️',
		defaultIsOpen: true,
		children: [
			{
				id: 'local-manage-sources',
				title: 'Sources',
				href: '/~/manage/sources',
				icon: '📡',
			},
		],
	},
] satisfies NavigationItem[]
