export const activeRoots = [
	'src/schema',
	'src/views',
	'src/routes',
	'src/sources',
	'src/resolvers',
] as const

export const referenceRoots = [
	'src/schema_',
	'src/views_',
	'src/views__',
	'src/routes_',
	'src/sources_',
	'src/resolvers_',
] as const

export const documentWitnesses = [
	'AGENTS.md',
	'APP-PLAN.md',
	'RESOLVER-COVERAGE.md',
	'ROUTE-DEFINITIONS.ts',
	'SCHEMA.md',
	'SOURCES.md',
	'package.json',
] as const

export const generatedMarkers = [
	'Generated by',
	'generated by',
	'THIS FILE IS GENERATED',
	'This file is generated',
	'@generated',
] as const
