// Generated from APP.ts.

import type { RegisteredSourceResolverModule } from '$/resolvers/defineResolver.ts'
import { Source } from '$/sources/Source.ts'

type ResolverLoaderEntry = {
	[_Source in Source]: readonly [
		_Source,
		() => Promise<{
			default: RegisteredSourceResolverModule<_Source>
		}>,
	]
}[Source]

const resolverLoaderEntries = [
	[Source.Aave_Rest, () => import('./Aave-Rest.ts')],
	[Source.AcpRegistry_Rest, () => import('./AcpRegistry-Rest.ts')],
	[Source.Across_Rest, () => import('./Across-Rest.ts')],
	[Source.Allium_Rest, () => import('./Allium-Rest.ts')],
	[Source.Amboss_Graphql, () => import('./Amboss-Graphql.ts')],
	[Source.AptosFullnode_Rest, () => import('./AptosFullnode-Rest.ts')],
	[Source.AptosIndexer_Graphql, () => import('./AptosIndexer-Graphql.ts')],
	[Source.Arweave_Graphql, () => import('./Arweave-Graphql.ts')],
	[Source.Arweave_Rest, () => import('./Arweave-Rest.ts')],
	[Source.Atproto_BskySocial_Xrpc, () => import('./Atproto-BskySocial-Xrpc.ts')],
	[Source.Atproto_Xrpc, () => import('./Atproto-Xrpc.ts')],
	[Source.AtprotoSync_Xrpc, () => import('./AtprotoSync-Xrpc.ts')],
	[Source.Avail, () => import('./Avail-JsonRpc.ts')],
	[Source.AvalancheInfo_JsonRpc, () => import('./AvalancheInfo-JsonRpc.ts')],
	[Source.AvalanchePlatformVm_JsonRpc, () => import('./AvalanchePlatformVm-JsonRpc.ts')],
	[Source.Axelarscan_Rest, () => import('./Axelarscan-Rest.ts')],
	[Source.Balancer_Rest, () => import('./Balancer-Rest.ts')],
	[Source.Beacon_Rest, () => import('./Beacon-Rest.ts')],
	[Source.BeaconchaIn_Rest, () => import('./BeaconchaIn-Rest.ts')],
	[Source.BitcoinBips_Github, () => import('./BitcoinBips-Github.ts')],
	[Source.BitcoinCashBcmr_Github, () => import('./BitcoinCashBcmr-Github.ts')],
	[Source.BitcoinCashChips_Gitlab, () => import('./BitcoinCashChips-Gitlab.ts')],
	[Source.BitcoinCashNode_JsonRpc, () => import('./BitcoinCashNode-JsonRpc.ts')],
	[Source.BitcoinCore_JsonRpc, () => import('./BitcoinCore-JsonRpc.ts')],
	[Source.Bithomp, () => import('./Bithomp.ts')],
	[Source.Bittensor_JsonRpc, () => import('./Bittensor-JsonRpc.ts')],
	[Source.Blobscan_Rest, () => import('./Blobscan-Rest.ts')],
	[Source.Blockchair_Rest, () => import('./Blockchair-Rest.ts')],
	[Source.Blockfrost_Rest, () => import('./Blockfrost-Rest.ts')],
	[Source.Blockscout_Rest, () => import('./Blockscout-Rest.ts')],
	[Source.Caips_Github, () => import('./Caips-Github.ts')],
	[Source.CardanoKoios_Rest, () => import('./CardanoKoios-Rest.ts')],
	[Source.Cardanoscan_Rest, () => import('./Cardanoscan-Rest.ts')],
	[Source.CashuMint_Rest, () => import('./CashuMint-Rest.ts')],
	[Source.Celenium_Rest, () => import('./Celenium-Rest.ts')],
	[Source.CelestiaNode, () => import('./CelestiaNode-JsonRpc.ts')],
	[Source.ChainlinkDataFeeds_AddressCatalog, () => import('./ChainlinkDataFeeds-AddressCatalog.ts')],
	[Source.ChainlinkDataFeeds_Contracts, () => import('./ChainlinkDataFeeds-Contracts.ts')],
	[Source.Chainlist_Rest, () => import('./Chainlist-Rest.ts')],
	[Source.CircleCctpContracts_Evm, () => import('./CircleCctpContracts-Evm.ts')],
	[Source.CircleCctpContracts_Solana, () => import('./CircleCctpContracts-Solana.ts')],
	[Source.CircleCctpContracts_Stellar, () => import('./CircleCctpContracts-Stellar.ts')],
	[Source.CircleCctpIris, () => import('./CircleCctp-Rest.ts')],
	[Source.Coingecko_Rest, () => import('./Coingecko-Rest.ts')],
	[Source.CoinMarketCap_Rest, () => import('./CoinMarketCap-Rest.ts')],
	[Source.Coinpaprika_Rest, () => import('./Coinpaprika-Rest.ts')],
	[Source.CometBft_Rest, () => import('./CometBft-Rest.ts')],
	[Source.Compound_Rest, () => import('./Compound-Rest.ts')],
	[Source.Constants_Internal, () => import('./Constants.ts')],
	[Source.CosmosAdrs_Github, () => import('./CosmosAdrs-Github.ts')],
	[Source.CosmosChainRegistry_Github, () => import('./CosmosChainRegistry-Github.ts')],
	[Source.CosmosSdk_Rest, () => import('./CosmosSdk-Rest.ts')],
	[Source.Curve_Rest, () => import('./Curve-Rest.ts')],
	[Source.Defillama_Rest, () => import('./Defillama-Rest.ts')],
	[Source.Dexscreener_Rest, () => import('./Dexscreener-Rest.ts')],
	[Source.DogecoinCore_JsonRpc, () => import('./DogecoinCore-JsonRpc.ts')],
	[Source.DogecoinDips_Github, () => import('./DogecoinDips-Github.ts')],
	[Source.Dune_Rest, () => import('./Dune-Rest.ts')],
	[Source.DydxIndexer, () => import('./Dydx.ts')],
	[Source.EasScan_Graphql, () => import('./EasScan-Graphql.ts')],
	[Source.EigenExplorer_Rest, () => import('./EigenExplorer-Rest.ts')],
	[Source.Eip8004Scan_Rest, () => import('./Eip8004Scan-Rest.ts')],
	[Source.Ensips_Github, () => import('./Ensips-Github.ts')],
	[Source.EnvioHyperRpc_JsonRpc, () => import('./Envio-HyperRpc.ts')],
	[Source.EnvioHyperSync_RawHttp, () => import('./Envio-HyperSync.ts')],
	[Source.Esplora_Rest, () => import('./Esplora-Rest.ts')],
	[Source.EthereumEips_Github, () => import('./EthereumEips-Github.ts')],
	[Source.EthereumLists_Rest, () => import('./EthereumLists-Chains.ts')],
	[Source.EthereumSpecs_Github, () => import('./EthereumSpecs-Github.ts')],
	[Source.Etherscan_Rest, () => import('./Etherscan-Rest.ts')],
	[Source.Euler_Rest, () => import('./Euler-Rest.ts')],
	[Source.Farcaster_Rest, () => import('./Farcaster-Rest.ts')],
	[Source.FedimintGatewayd_Rest, () => import('./FedimintGatewayd-Rest.ts')],
	[Source.FilecoinFips_Github, () => import('./FilecoinFips-Github.ts')],
	[Source.Filfox_Rest, () => import('./Filfox-Rest.ts')],
	[Source.FourByteDirectory_Rest, () => import('./FourByteDirectory-Rest.ts')],
	[Source.GetBlockRpc_JsonRpc, () => import('./GetBlock-Rpc.ts')],
	[Source.GetBlockYellowstone_Grpc, () => import('./GetBlock-Yellowstone.ts')],
	[Source.Gitlab_Rest, () => import('./Gitlab-Rest.ts')],
	[Source.Gmx_Rest, () => import('./Gmx-Rest.ts')],
	[Source.GoldRushFoundational_Rest, () => import('./Covalent-Rest.ts')],
	[Source.HederaMirrorNode_Rest, () => import('./HederaMirrorNode-Rest.ts')],
	[Source.Helius, () => import('./Helius.ts')],
	[Source.HuggingFaceHub_Rest, () => import('./HuggingFaceHub-Rest.ts')],
	[Source.Hyperliquid, () => import('./Hyperliquid.ts')],
	[Source.HyperliquidDocs_Rest, () => import('./HyperliquidDocs-Rest.ts')],
	[Source.InternetComputer_RosettaApi, () => import('./InternetComputer-RosettaApi.ts')],
	[Source.Ipfs_Rest, () => import('./Ipfs-Rest.ts')],
	[Source.KaspaExplorer, () => import('./KaspaExplorer.ts')],
	[Source.KingnodesDydxNode, () => import('./Kingnodes-Rest.ts')],
	[Source.L2Beat_Rest, () => import('./L2Beat-Rest.ts')],
	[Source.LayerZeroScan_Rest, () => import('./LayerZeroScan-Rest.ts')],
	[Source.Lens_Graphql, () => import('./Lens-Graphql.ts')],
	[Source.Lifi_Rest, () => import('./Lifi-Rest.ts')],
	[Source.LightningLnd_Rest, () => import('./LightningLnd-Rest.ts')],
	[Source.LightningMempoolSpace_Rest, () => import('./LightningMempoolSpace-Rest.ts')],
	[Source.LitecoinCore_JsonRpc, () => import('./LitecoinCore-JsonRpc.ts')],
	[Source.LitecoinLips_Github, () => import('./LitecoinLips-Github.ts')],
	[Source.Local_Internal, () => import('./Local.ts')],
	[Source.LogosBlockchainNode_Rest, () => import('./LogosBlockchainNode-Rest.ts')],
	[Source.Lotus_JsonRpc, () => import('./Lotus-JsonRpc.ts')],
	[Source.MagnetUri_Uri, () => import('./MagnetUri-Uri.ts')],
	[Source.Mastodon_Rest, () => import('./Mastodon-Rest.ts')],
	[Source.McpPackageRegistry_Rest, () => import('./McpPackageRegistry-Rest.ts')],
	[Source.MempoolSpace_Rest, () => import('./MempoolSpace-Rest.ts')],
	[Source.MetadataVision_Rest, () => import('./MetadataVision-Rest.ts')],
	[Source.MevRelay_Rest, () => import('./MevRelay-Rest.ts')],
	[Source.Mintscan, () => import('./Mintscan.ts')],
	[Source.Mlflow_Rest, () => import('./Mlflow-Rest.ts')],
	[Source.MoneroDaemonRpc_JsonRpc, () => import('./MoneroDaemonRpc-JsonRpc.ts')],
	[Source.Morpho_Graphql, () => import('./Morpho-Graphql.ts')],
	[Source.Morpho_Rest, () => import('./Morpho-Rest.ts')],
	[Source.NearBlocks_Rest, () => import('./NearBlocks-Rest.ts')],
	[Source.NearNeps_Github, () => import('./NearNeps-Github.ts')],
	[Source.NearRpc_JsonRpc, () => import('./NearRpc-JsonRpc.ts')],
	[Source.Neynar_Rest, () => import('./Neynar-Rest.ts')],
	[Source.Nodely, async () => {
		const [
			algodRest,
			algorandIndexerRest,
		] = await Promise.all([
			import('./Algod-Rest.ts'),
			import('./AlgorandIndexer-Rest.ts'),
		])
		return {
			default: {
				source: Source.Nodely,
				resolvers: [
					...algodRest.default.resolvers,
					...algorandIndexerRest.default.resolvers,
				],
			},
		}
	}],
	[Source.NostrRelay_Nip11_Http, () => import('./NostrRelay-Nip11-Http.ts')],
	[Source.NostrRelay_WebSocket, () => import('./NostrRelay-WebSocket.ts')],
	[Source.Ogmios_JsonRpc, () => import('./Ogmios-JsonRpc.ts')],
	[Source.OpenAI_Rest, () => import('./OpenAI-Rest.ts')],
	[Source.Openchain_Rest, () => import('./Openchain-Rest.ts')],
	[Source.OpenSea_Rest, () => import('./OpenSea-Rest.ts')],
	[Source.Osmosis_LCD_Rest, () => import('./Osmosis-Rest.ts')],
	[Source.Pathfinder, () => import('./Pathfinder.ts')],
	[Source.PayjoinDirectory_Rest, () => import('./PayjoinDirectory-Rest.ts')],
	[Source.Pendle_Rest, () => import('./Pendle-Rest.ts')],
	[Source.Piped_Rest, () => import('./Piped-Rest.ts')],
	[Source.Polkadot_JsonRpc, () => import('./Polkadot-JsonRpc.ts')],
	[Source.PolkadotRfcs_Github, () => import('./PolkadotRfcs-Github.ts')],
	[Source.Primal_Rest, () => import('./Primal-Rest.ts')],
	[Source.PythBenchmarks_Rest, () => import('./PythBenchmarks-Rest.ts')],
	[Source.PythHermes_Rest, () => import('./PythHermes-Rest.ts')],
	[Source.qBittorrentWebUi_Rest, () => import('./qBittorrentWebUi-Rest.ts')],
	[Source.QuilibriumDocs_Rest, () => import('./QuilibriumDocs-Rest.ts')],
	[Source.QuilibriumNodeMetrics_Prometheus, () => import('./QuilibriumNodeMetrics-Prometheus.ts')],
	[Source.QuilibriumNodeRpc_Grpc, () => import('./QuilibriumNodeRpc-Grpc.ts')],
	[Source.Reddit_PublicJson, () => import('./Reddit-PublicJson.ts')],
	[Source.Reddit_Rest, () => import('./Reddit-Rest.ts')],
	[Source.Rss_Rest, () => import('./Rss-Rest.ts')],
	[Source.Rss2Json_Rest, () => import('./Rss2Json-Rest.ts')],
	[Source.SafeTransactionService_Rest, () => import('./Safe-Rest.ts')],
	[Source.Snapchain_Rest, () => import('./Snapchain-Rest.ts')],
	[Source.SnapshotHub_Graphql, () => import('./SnapshotHub-Graphql.ts')],
	[Source.Solana_JsonRpc, () => import('./Solana-JsonRpc.ts')],
	[Source.SolanaSimds_Github, () => import('./SolanaSimds-Github.ts')],
	[Source.Sourcify_Rest, () => import('./Sourcify-Rest.ts')],
	[Source.SpaceAndTime_MakeInfinite, () => import('./SpaceAndTime-MakeInfinite.ts')],
	[Source.SqdPortal_RawHttp, () => import('./Sqd-Portal.ts')],
	[Source.Starkscan, () => import('./Starkscan.ts')],
	[Source.StellarExpert, () => import('./StellarExpert.ts')],
	[Source.StellarHorizon_Rest, () => import('./StellarHorizon-Rest.ts')],
	[Source.Subscan_Rest, () => import('./Subscan-Rest.ts')],
	[Source.SubstrateSidecar_Rest, () => import('./SubstrateSidecar-Rest.ts')],
	[Source.Sui, () => import('./Sui.ts')],
	[Source.Superchain_Github, () => import('./Superchain-Github.ts')],
	[Source.Swarm_Rest, () => import('./Swarm-Rest.ts')],
	[Source.Tally, () => import('./Tally-Graphql.ts')],
	[Source.TezosDappetizer_Postgres, () => import('./TezosDappetizer-Postgres.ts')],
	[Source.TheGraph_Graphql, () => import('./Ens-TheGraph.ts')],
	[Source.ThreeXpl_Rest, () => import('./ThreeXpl-Rest.ts')],
	[Source.TonApi_Rest, () => import('./TonApi-Rest.ts')],
	[Source.TonCenter, () => import('./TonCenter.ts')],
	[Source.TradingView_Rest, () => import('./TradingView-Rest.ts')],
	[Source.TronFullNode_Rest, () => import('./TronFullNode-Rest.ts')],
	[Source.TronGrid_Rest, () => import('./TronGrid-Rest.ts')],
	[Source.TronScan_Rest, () => import('./TronScan-Rest.ts')],
	[Source.TronSolidityNode_Rest, () => import('./TronSolidityNode-Rest.ts')],
	[Source.TrustWalletAssets_Github, () => import('./TrustWalletAssets-Github.ts')],
	[Source.Tzkt_Rest, () => import('./Tzkt-Rest.ts')],
	[Source.UniSat_Rest, () => import('./UniSat-Rest.ts')],
	[Source.UniswapContracts_Evm, () => import('./UniswapContracts-Evm.ts')],
	[Source.Voltaire_JsonRpc, () => import('./Voltaire-JsonRpc.ts')],
	[Source.Voyager, () => import('./Voyager-Rest.ts')],
	[Source.WakuNode, () => import('./WakuNode-Rest.ts')],
	[Source.Wormholescan, () => import('./Wormholescan-Rest.ts')],
	[Source.X_FxEmbed_Rest, () => import('./X-FxEmbed-Rest.ts')],
	[Source.X_Rest, () => import('./X-Rest.ts')],
	[Source.Xrpl_Rippled, () => import('./Xrpl-JsonRpc.ts')],
	[Source.XrplClio_JsonRpc, () => import('./XrplClio-JsonRpc.ts')],
	[Source.XrpScan_Rest, () => import('./XrpScan-Rest.ts')],
	[Source.Youtube_Rest, () => import('./Youtube-Rest.ts')],
	[Source.Zcashd_JsonRpc, () => import('./Zcashd-JsonRpc.ts')],
	[Source.ZcashZips_Github, () => import('./ZcashZips-Github.ts')],
	[Source.Zebra_JsonRpc, () => import('./Zebra-JsonRpc.ts')],
	[Source.ZeroGChain_JsonRpc, () => import('./ZeroGChain-JsonRpc.ts')],
	[Source.ZeroGChainScan_Rest, () => import('./ZeroGChainScan-Rest.ts')],
	[Source.ZeroGStorageNode_JsonRpc, () => import('./ZeroGStorageNode-JsonRpc.ts')],
	[Source.ZeroGStorageScan_Rest, () => import('./ZeroGStorageScan-Rest.ts')],
] as const satisfies readonly ResolverLoaderEntry[]

export const loadResolvers = async (enabledSources: ReadonlySet<Source> = new Set(Object.values(Source))) => Promise.all(
	resolverLoaderEntries
		.filter(([source]) => enabledSources.has(source))
		.map(async ([source, load]) => {
			const resolverModule = (await load()).default
			if (resolverModule.source !== source)
				throw new Error(`Resolver module source mismatch: expected ${source}, received ${resolverModule.source}`)

			return resolverModule
		})
)
