import { stringify } from 'devalue'

import {
	atprotoProbeDid,
	atprotoProbePostUri,
} from '$/constants/Social/Atproto.ts'
import {
	CAST_HASH_32,
	e2eNostrYouTubeOptionalDetailRoutePaths,
	e2eNostrYouTubeRoutePaths,
	SAMPLE_BLOB_TX_HASH,
} from '$/routes/api/e2e/assert-loaded-resolvers/_fixtures.ts'


/** Routes exercised by `route-views-smoke.e2e.ts` and boundary-settle checks. */
const SAMPLE_TX_HASH = (
	'0xdacd6abf5b2814b28c68c59981f269c615796e7f0cba2009f4bf5edfdd9595ab' as const
)

const MARKET_KEY_ETH_USD_BINANCE = stringify({
	$base: { kind: 'Coin', $coin: { coinId: 'ETH' } },
	$quote: { kind: 'Currency', $currency: { iso4217: 'USD' } },
	$marketVenue: { marketVenueId: 'Binance' },
	marketKind: 'Spot',
})

const RSS_PROBE_FEED_URL = 'https://blog.svelte.dev/feed.xml' as const

export const ADDR = '0xd8da6bf26964af9d7eed9e403e826090792bed6a' as const

/** Detail routes depending on live NostrBand / YouTube / Piped payloads (not in default smoke set). */
export const routeViewSmokeOptionalDetailPathByLabel: Record<string, `/${string}`> = (
	e2eNostrYouTubeOptionalDetailRoutePaths
)

export const routeViewSmokePathByLabel: Record<string, `/${string}`> = {
	exploreHub: '/explore',
	assetsHub: '/assets',
	accountsHub: '/~/accounts',
	proposalsHub: '/proposals',
	proposalKindDetail: '/proposals/ethereum/eip',
	proposalDetail: '/proposals/ethereum/eip/eip-1559',
	networkDetail: '/network/eip155:1',
	networkBlocks: '/network/eip155:1/blocks',
	networkTransactions: '/network/eip155:1/transactions',
	networkContracts: '/network/eip155:1/contracts',
	networkBlobs: '/network/eip155:1/blobs',
	networkBlobDetail: `/network/eip155:1/blob/${SAMPLE_BLOB_TX_HASH}/0`,
	networkBeaconSlots: '/network/eip155:1/beacon-slots',
	networkUpgrades: '/network/eip155:1/upgrades',
	networkBlock: '/network/eip155:1/block/18000000',
	networkTransaction: `/network/eip155:1/tx/${SAMPLE_TX_HASH}`,
	networkTransactionLog: `/network/eip155:1/tx/${SAMPLE_TX_HASH}/log/0`,
	evmHub: '/evm',
	evmCalldata: '/evm/calldata',
	evmCalldataDecoder: '/evm/calldata-decoder',
	evmErrors: '/evm/errors',
	contractsGlobal: '/contracts',
	upgradesGlobal: '/upgrades',
	ensHub: '/ens',
	ensNameDetail: '/ens/name/vitalik.eth',
	farcasterHub: '/farcaster',
	farcasterUsers: '/farcaster/users',
	farcasterChannels: '/farcaster/channels',
	farcasterFeeds: '/farcaster/feed',
	farcasterUserDetail: '/farcaster/user/3',
	farcasterCastDetail: `/farcaster/cast/3/${CAST_HASH_32}`,
	xHub: '/x',
	xUsers: '/x/users',
	xPosts: '/x/posts',
	xUserDetail: '/x/user/12',
	xPostDetail: '/x/post/1855943488122347520',
	atprotoHub: '/atproto',
	atprotoActors: '/atproto/actors',
	atprotoPosts: '/atproto/posts',
	atprotoActor: `/atproto/actor/${atprotoProbeDid}`,
	atprotoActorPosts: `/atproto/actor/${atprotoProbeDid}/posts`,
	atprotoPostDetail: `/atproto/post/${encodeURIComponent(atprotoProbePostUri)}`,
	activitypubHub: '/activitypub',
	activitypubActors: '/activitypub/actors',
	activitypubNotes: '/activitypub/notes',
	activitypubActor: '/activitypub/actor/https%3A%2F%2Fmastodon.social/13179',
	activitypubNote: '/activitypub/note/https%3A%2F%2Fmastodon.social/116539053870420123',
	redditHub: '/reddit',
	redditSubreddits: '/reddit/subreddits',
	redditLinks: '/reddit/links',
	redditSubredditDetail: '/reddit/r/ethereum',
	redditLinkDetail: '/reddit/link/t3_1h7t8a',
	redditCommentDetail: '/reddit/comment/t1_carprdq',
	redditCommentReplies: '/reddit/comment/t1_carprdq/replies',
	rssHub: '/rss',
	rssFeeds: '/rss/feeds',
	rssItems: '/rss/items',
	rssFeedDetail: `/rss/feed/${encodeURIComponent(RSS_PROBE_FEED_URL)}`,
	lensHub: '/lens',
	lensAccounts: '/lens/accounts',
	lensPosts: '/lens/posts',
	nostrHub: '/nostr',
	nostrProfiles: '/nostr/profiles',
	nostrNotes: '/nostr/notes',
	...e2eNostrYouTubeRoutePaths,
	xmtpHub: '/xmtp',
	xmtpConversations: '/xmtp/conversations',
	xmtpAccounts: '/xmtp/accounts',
	xmtpConversationDetail: '/xmtp/conversation/e2e-probe-conversation',
	youtubeHub: '/youtube',
	youtubeChannelPlaylists: `/youtube/channel/${encodeURIComponent('UC_x5XG1OV2P6uZZ5FSM9Ttw')}/playlists`,
	ipfsHub: '/ipfs',
	ipfsResourceCidEncodings: '/ipfs/ipfs/QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG',
	swarmHub: '/swarm',
	swarmResourceDocsLanding: '/swarm/8b6ca499eb6f3f7e5ee242f08f1de2e7e6bb1728d7f4ee5ec22091b048f34ff1',
	swarmResourceManifestPath: '/swarm/8b6ca499eb6f3f7e5ee242f08f1de2e7e6bb1728d7f4ee5ec22091b048f34ff1/path/index.html',
	coinsHub: '/coins',
	coinsCoinEth: '/coin/ETH',
	coinsCandles: '/coins/candles',
	coinsPrices: '/coins/prices',
	marketsHub: '/markets',
	marketsMarketEthUsdBinance: `/market/${encodeURIComponent(MARKET_KEY_ETH_USD_BINANCE)}`,
	marketsMarketInvalid: '/market/%7B%7D',
	marketVenuesHub: '/market-venues',
	marketVenuesBinance: '/market-venue/Binance',
	vaultsHub: '/vaults',
	vaultDetail: '/vault/1/0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640',
	poolsHub: '/pools',
	poolDetail: '/pool/1/0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640',
	channelsHub: '/channels',
	channelsChannelDetail: '/channel/e2e-probe-state-channel',
	leverageHub: '/leverage',
	servicesHub: '/services',
	agentServicesList: '/services/agents',
	agentServiceDetail: '/services/agent/56/104776',
	agentsConversationsList: '/~/agents/conversations',
	agentConversationWorkspace: '/~/agents/conversation/e2e-probe-agent-conversation',
	socialHub: '/social',
	exploreManage: '/~/manage',
	multiplayerHub: '/~/multiplayer',
	multiplayerRooms: '/~/multiplayer/rooms',
	multiplayerContacts: '/~/multiplayer/contacts',
	multiplayerRoomDetail: '/~/multiplayer/room/e2e-probe-room',
	multiplayerContactDetail: '/~/multiplayer/contact/e2e-probe-room-peer',
	dashboardsHub: '/~/dashboards',
	accountActor: `/account/${ADDR}`,
	accountActorNetwork: `/network/eip155:1/account/${ADDR}`,
	coinInstanceNative: '/coin-instance/1/native',
	liquidityPositions: '/~/accounts/positions',
	bridgeTransactionsList: '/~/accounts/transactions',
	bridgeTransactionDetail: `/~/accounts/transaction/1/${ADDR}/${SAMPLE_TX_HASH}/0`,
	lensAccount: `/lens/account/${ADDR}`,
	lensAccountPosts: `/lens/account/${ADDR}/posts`,
	lensPost: `/lens/post/${encodeURIComponent('161m1s2r2av9deyh2a3')}`,
	evmSelectors: '/evm/selectors',
	evmTopics: '/evm/topics',
}
