/** Routes exercised by `route-views-smoke.e2e.ts` and boundary-settle checks. */
export const ADDR = '0xd8da6bf26964af9d7eed9e403e826090792bed6a' as const

export const routeViewSmokePathByLabel: Record<string, `/${string}`> = {
	exploreHub: '/explore',
	assetsHub: '/assets',
	accountsHub: '/~/accounts',
	proposalsHub: '/proposals',
	networkDetail: '/network/1',
	networkBlocks: '/network/1/blocks',
	networkTransactions: '/network/1/transactions',
	networkContracts: '/network/1/contracts',
	networkBlobs: '/network/1/blobs',
	networkBeaconSlots: '/network/1/beacon-slots',
	networkUpgrades: '/network/1/upgrades',
	networkBlock: '/network/1/block/18000000',
	evmHub: '/evm',
	contractsGlobal: '/contracts',
	upgradesGlobal: '/upgrades',
	ensHub: '/ens',
	farcasterHub: '/farcaster',
	farcasterUsers: '/farcaster/users',
	farcasterChannels: '/farcaster/channels',
	farcasterFeeds: '/farcaster/feed',
	xHub: '/x',
	atprotoHub: '/atproto',
	activitypubHub: '/activitypub',
	redditHub: '/reddit',
	lensHub: '/lens',
	xmtpHub: '/xmtp',
	ipfsHub: '/ipfs',
	ipfsResourceCidEncodings: '/ipfs/ipfs/QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG',
	swarmHub: '/swarm',
	coinsHub: '/coins',
	coinsCoinEth: '/coin/ETH',
	coinsCandles: '/coins/candles',
	coinsPrices: '/coins/prices',
	marketsHub: '/markets',
	marketsMarketInvalid: '/market/%7B%7D',
	vaultsHub: '/vaults',
	poolsHub: '/pools',
	channelsHub: '/channels',
	leverageHub: '/leverage',
	agentsHub: '/agents',
	socialHub: '/social',
	exploreManage: '/~/manage',
	multiplayerHub: '/~/multiplayer',
	dashboardsHub: '/~/dashboards',
	accountActor: `/~/accounts/account/${ADDR}`,
	liquidityPositions: '/~/accounts/positions',
	lensAccount: `/lens/account/${ADDR}`,
	lensAccountPosts: `/lens/account/${ADDR}/posts`,
	lensPost: `/lens/post/${encodeURIComponent('0x0000000000000000000000000000000000000000000000000000000000000001')}`,
	atprotoActor: '/atproto/actor/did:plc:z72i7hdynmk6x22kvon7fdpk',
	evmSelectors: '/evm/selectors',
	evmTopics: '/evm/topics',
}
