import {
	e2eNostrYouTubeOptionalDetailRoutePaths,
	e2eNostrYouTubeRoutePaths,
} from '$/routes/api/e2e/assert-loaded-resolvers/_fixtures.ts'


/** Routes exercised by `route-views-smoke.e2e.ts` and boundary-settle checks. */
const SAMPLE_TX_HASH = (
	'0xdacd6abf5b2814b28c68c59981f269c615796e7f0cba2009f4bf5edfdd9595ab' as const
)

export const ADDR = '0xd8da6bf26964af9d7eed9e403e826090792bed6a' as const

/** Detail routes depending on live NostrBand / YouTube / Piped payloads (not in default smoke set). */
export const routeViewSmokeOptionalDetailPathByLabel: Record<string, `/${string}`> = (
	e2eNostrYouTubeOptionalDetailRoutePaths
)

export const routeViewSmokePathByLabel: Record<string, `/${string}`> = {
	exploreHub: '/explore',
	assetsHub: '/assets',
	accountsHub: '/~/accounts',
	proposalsHub: '/proposals',
	networkDetail: '/network/1',
	networkBlocks: '/network/1/blocks',
	networkTransactions: '/network/1/transactions',
	networkContracts: '/network/1/contracts',
	networkBlobs: '/network/1/blobs',
	networkBeaconSlots: '/network/1/beacon-slots',
	networkUpgrades: '/network/1/upgrades',
	networkBlock: '/network/1/block/18000000',
	networkTransaction: `/network/1/tx/${SAMPLE_TX_HASH}`,
	networkTransactionLog: `/network/1/tx/${SAMPLE_TX_HASH}/log/0`,
	evmHub: '/evm',
	evmCalldata: '/evm/calldata',
	evmCalldataDecoder: '/evm/calldata-decoder',
	evmErrors: '/evm/errors',
	contractsGlobal: '/contracts',
	upgradesGlobal: '/upgrades',
	ensHub: '/ens',
	farcasterHub: '/farcaster',
	farcasterUsers: '/farcaster/users',
	farcasterChannels: '/farcaster/channels',
	farcasterFeeds: '/farcaster/feed',
	xHub: '/x',
	xUsers: '/x/users',
	xPosts: '/x/posts',
	atprotoHub: '/atproto',
	atprotoActors: '/atproto/actors',
	atprotoPosts: '/atproto/posts',
	activitypubHub: '/activitypub',
	activitypubActors: '/activitypub/actors',
	activitypubNotes: '/activitypub/notes',
	redditHub: '/reddit',
	redditSubreddits: '/reddit/subreddits',
	redditLinks: '/reddit/links',
	rssHub: '/rss',
	rssFeeds: '/rss/feeds',
	rssItems: '/rss/items',
	lensHub: '/lens',
	lensAccounts: '/lens/accounts',
	lensPosts: '/lens/posts',
	nostrHub: '/nostr',
	nostrProfiles: '/nostr/profiles',
	nostrNotes: '/nostr/notes',
	...e2eNostrYouTubeRoutePaths,
	xmtpHub: '/xmtp',
	youtubeHub: '/youtube',
	ipfsHub: '/ipfs',
	ipfsResourceCidEncodings: '/ipfs/ipfs/QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG',
	swarmHub: '/swarm',
	coinsHub: '/coins',
	coinsCoinEth: '/coin/ETH',
	coinsCandles: '/coins/candles',
	coinsPrices: '/coins/prices',
	marketsHub: '/markets',
	marketsMarketInvalid: '/market/%7B%7D',
	marketVenuesHub: '/market-venues',
	marketVenuesBinance: '/market-venue/Binance',
	vaultsHub: '/vaults',
	poolsHub: '/pools',
	channelsHub: '/channels',
	leverageHub: '/leverage',
	agentsHub: '/agents',
	socialHub: '/social',
	exploreManage: '/~/manage',
	multiplayerHub: '/~/multiplayer',
	dashboardsHub: '/~/dashboards',
	accountActor: `/account/${ADDR}`,
	accountActorNetwork: `/network/1/account/${ADDR}`,
	coinInstanceNative: '/coin-instance/1/native',
	liquidityPositions: '/~/accounts/positions',
	lensAccount: `/lens/account/${ADDR}`,
	lensAccountPosts: `/lens/account/${ADDR}/posts`,
	lensPost: `/lens/post/${encodeURIComponent('0x0000000000000000000000000000000000000000000000000000000000000001')}`,
	atprotoActor: '/atproto/actor/did:plc:z72i7hdynmk6x22kvon7fdpk',
	evmSelectors: '/evm/selectors',
	evmTopics: '/evm/topics',
}
