/**
 * The OpenAPI contract generated by dYdX's Indexer service.
 * @see https://github.com/dydxprotocol/v4-chain/tree/main/indexer/services/comlink/public
 */
export const schemaSource = {
	schemaUrl: 'https://raw.githubusercontent.com/dydxprotocol/v4-chain/main/indexer/services/comlink/public/swagger.json',
	schemaFile: './openapi.json',
	typesFile: './openapi.d.ts',
} as const
