schema {
	query: Query
}

enum OrderDirection {
	asc
	desc
}

enum Market_orderBy {
	createdTimestamp
	name
	totalBorrowBalanceUSD
	totalDepositBalanceUSD
	totalValueLockedUSD
}

input LendingProtocol_filter {
	network: Network
	slug: String
}

input Market_filter {
	canBorrowFrom: Boolean
	inputToken: String
	isActive: Boolean
	protocol: String
}

type Query {
	lendingProtocols(
		first: Int
		where: LendingProtocol_filter
	): [LendingProtocol!]!

	market(id: Bytes!): Market

	markets(
		first: Int
		orderBy: Market_orderBy
		orderDirection: OrderDirection
		where: Market_filter
	): [Market!]!
}
