/**
 * Default execution endpoints by chain: url, serviceProvider, transportType.
 */

// Types
import { ChainId } from '$/constants/ChainId.ts'
import { ExecutionRpcProvider } from '$/constants/ExecutionRpcProvider.ts'
import { TransportType } from '$/constants/TransportType.ts'

/** Execution client / user agent from web3_clientVersion. Probed for HTTP endpoints to correlate with tevmForkTransportCompatible. */
export enum ExecutionClientId {
	Geth = 'Geth',
	Erigon = 'Erigon',
	Nethermind = 'Nethermind',
	OpenEthereum = 'OpenEthereum',
	Besu = 'Besu',
	Reth = 'Reth',
	Other = 'Other',
	Unknown = 'Unknown',
}

export type ExecutionEndpoint = {
	chainId: ChainId
	url: string
	serviceProvider: ExecutionRpcProvider
	transportType: TransportType
	/** When true, Tevm fork (createTevmNode + ready + getVm) succeeds against this RPC; when false, it throws (e.g. @noble/curves or @noble/hashes abytes: “expected Uint8Array, got type=undefined” because some RPCs return null/undefined for fields used as bytes). Omit for WebSocket or when unknown. */
	tevmForkTransportCompatible?: boolean
	/** From web3_clientVersion; omit for WebSocket or when not probed. */
	executionClient?: ExecutionClientId
}


// Constants
export const executionEndpoints = [
	// {
	// 	chainId: ChainId.Ethereum,
	// 	// url: 'http://149.88.21.34:8545',
	// 	// url: 'http://192.168.9.219:8545',
	// 	url: 'http://100.73.81.63:8545',
	// 	serviceProvider: ExecutionRpcProvider.Local,
	// 	transportType: TransportType.Http,
	// },
	// {
	// 	chainId: ChainId.Ethereum,
	// 	url: 'ws://100.73.81.63:8546',
	// 	serviceProvider: ExecutionRpcProvider.Local,
	// 	transportType: TransportType.WebSocket,
	// },
	// Public HTTP first so simulation/fork works in browser without a local node
	{
		chainId: ChainId.Ethereum,
		url: 'https://ethereum.publicnode.com',
		serviceProvider: ExecutionRpcProvider.PublicNode,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Geth,
	},
	{
		chainId: ChainId.Ethereum,
		url: 'wss://ethereum.publicnode.com',
		serviceProvider: ExecutionRpcProvider.PublicNode,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.Ethereum,
		url: 'http://localhost:8545',
		serviceProvider: ExecutionRpcProvider.Local,
		transportType: TransportType.Http,
	},
	{
		chainId: ChainId.Ethereum,
		url: 'ws://localhost:8545',
		serviceProvider: ExecutionRpcProvider.Local,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.Ethereum,
		url: 'https://eth.llamarpc.com',
		serviceProvider: ExecutionRpcProvider.LlamaNodes,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: false,
		executionClient: ExecutionClientId.Unknown,
	},
	{
		chainId: ChainId.Ethereum,
		url: 'wss://eth.llamarpc.com',
		serviceProvider: ExecutionRpcProvider.LlamaNodes,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.Ethereum,
		url: 'wss://mainnet.rpc.buidlguidl.com',
		serviceProvider: ExecutionRpcProvider.BuidlGuidl,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.Ethereum,
		url: 'https://mainnet.rpc.buidlguidl.com',
		serviceProvider: ExecutionRpcProvider.BuidlGuidl,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Unknown,
	},
	{
		chainId: ChainId.Ethereum,
		url: 'https://evm.stupidtech.net',
		serviceProvider: ExecutionRpcProvider.Unknown,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Unknown,
	},
	{
		chainId: ChainId.Optimism,
		url: 'https://mainnet.optimism.io',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Reth,
	},
	{
		chainId: ChainId.Optimism,
		url: 'wss://mainnet.optimism.io',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.XDC,
		url: 'https://erpc.xinfin.network',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Other,
	},
	{
		chainId: ChainId.XDC,
		url: 'wss://erpc.xinfin.network',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.XDCApothem,
		url: 'https://rpc.apothem.network',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Other,
	},
	{
		chainId: ChainId.XDCApothem,
		url: 'wss://rpc.apothem.network',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.Unichain,
		url: 'https://unichain-rpc.publicnode.com',
		serviceProvider: ExecutionRpcProvider.PublicNode,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Geth,
	},
	{
		chainId: ChainId.Unichain,
		url: 'wss://unichain-rpc.publicnode.com',
		serviceProvider: ExecutionRpcProvider.PublicNode,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.Monad,
		url: 'https://rpc.monad.xyz',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Other,
	},
	{
		chainId: ChainId.Monad,
		url: 'wss://rpc.monad.xyz',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.Sonic,
		url: 'https://rpc.soniclabs.com',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Other,
	},
	{
		chainId: ChainId.Sonic,
		url: 'wss://rpc.soniclabs.com',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.ZkSyncEraSepolia,
		url: 'https://sepolia.era.zksync.dev',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Other,
	},
	{
		chainId: ChainId.ZkSyncEraSepolia,
		url: 'wss://sepolia.era.zksync.dev',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.ZkSyncEra,
		url: 'https://mainnet.era.zksync.io',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Other,
	},
	{
		chainId: ChainId.ZkSyncEra,
		url: 'wss://mainnet.era.zksync.io',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.Polygon,
		url: 'https://polygon-rpc.com',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: false,
		executionClient: ExecutionClientId.Unknown,
	},
	{
		chainId: ChainId.Polygon,
		url: 'wss://polygon-rpc.com',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.WorldChain,
		url: 'https://worldchain-mainnet.g.alchemy.com/public',
		serviceProvider: ExecutionRpcProvider.Alchemy,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Reth,
	},
	{
		chainId: ChainId.WorldChain,
		url: 'wss://worldchain-mainnet.g.alchemy.com/public',
		serviceProvider: ExecutionRpcProvider.Alchemy,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.HyperEVM,
		url: 'https://hyperliquid.drpc.org',
		serviceProvider: ExecutionRpcProvider.PublicNode,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Geth,
	},
	{
		chainId: ChainId.HyperEVM,
		url: 'wss://hyperliquid.drpc.org',
		serviceProvider: ExecutionRpcProvider.PublicNode,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.HyperEVMTestnet,
		url: 'https://hyperliquid-testnet.drpc.org',
		serviceProvider: ExecutionRpcProvider.PublicNode,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Geth,
	},
	{
		chainId: ChainId.HyperEVMTestnet,
		url: 'wss://hyperliquid-testnet.drpc.org',
		serviceProvider: ExecutionRpcProvider.PublicNode,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.Sei,
		url: 'https://evm-rpc.sei-apis.com',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Geth,
	},
	{
		chainId: ChainId.Sei,
		url: 'wss://evm-rpc.sei-apis.com',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.SeiTestnet,
		url: 'https://evm-rpc-testnet.sei-apis.com',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Geth,
	},
	{
		chainId: ChainId.SeiTestnet,
		url: 'wss://evm-rpc-testnet.sei-apis.com',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.Arbitrum,
		url: 'https://arb1.arbitrum.io/rpc',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Other,
	},
	{
		chainId: ChainId.Arbitrum,
		url: 'wss://arb1.arbitrum.io/rpc',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.ArbitrumSepolia,
		url: 'https://sepolia-rollup.arbitrum.io/rpc',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Other,
	},
	{
		chainId: ChainId.ArbitrumSepolia,
		url: 'wss://sepolia-rollup.arbitrum.io/rpc',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.Avalanche,
		url: 'https://api.avax.network/ext/bc/C/rpc',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Other,
	},
	{
		chainId: ChainId.Avalanche,
		url: 'wss://api.avax.network/ext/bc/C/rpc',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.AvalancheFuji,
		url: 'https://api.avax-test.network/ext/bc/C/rpc',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Other,
	},
	{
		chainId: ChainId.AvalancheFuji,
		url: 'wss://api.avax-test.network/ext/bc/C/rpc',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.Celo,
		url: 'https://forno.celo.org',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Geth,
	},
	{
		chainId: ChainId.Celo,
		url: 'wss://forno.celo.org',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.Base,
		url: 'https://mainnet.base.org',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Geth,
	},
	{
		chainId: ChainId.Base,
		url: 'wss://mainnet.base.org',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.Base,
		url: 'https://base.llamarpc.com',
		serviceProvider: ExecutionRpcProvider.LlamaNodes,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Other,
	},
	{
		chainId: ChainId.Base,
		url: 'wss://base.llamarpc.com',
		serviceProvider: ExecutionRpcProvider.LlamaNodes,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.BNB,
		url: 'https://binance.llamarpc.com',
		serviceProvider: ExecutionRpcProvider.LlamaNodes,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Other,
	},
	{
		chainId: ChainId.BNB,
		url: 'wss://binance.llamarpc.com',
		serviceProvider: ExecutionRpcProvider.LlamaNodes,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.BaseSepolia,
		url: 'https://sepolia.base.org',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Geth,
	},
	{
		chainId: ChainId.BaseSepolia,
		url: 'wss://sepolia.base.org',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.Ink,
		url: 'https://rpc-gel.inkonchain.com',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Reth,
	},
	{
		chainId: ChainId.Ink,
		url: 'wss://rpc-gel.inkonchain.com',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.InkTestnet,
		url: 'https://rpc-gel-sepolia.inkonchain.com',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Reth,
	},
	{
		chainId: ChainId.InkTestnet,
		url: 'wss://rpc-gel-sepolia.inkonchain.com',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.Linea,
		url: 'https://rpc.linea.build',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Geth,
	},
	{
		chainId: ChainId.Linea,
		url: 'wss://rpc.linea.build',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.LineaSepolia,
		url: 'https://rpc.sepolia.linea.build',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Besu,
	},
	{
		chainId: ChainId.LineaSepolia,
		url: 'wss://rpc.sepolia.linea.build',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.PolygonAmoy,
		url: 'https://rpc-amoy.polygon.technology',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Other,
	},
	{
		chainId: ChainId.PolygonAmoy,
		url: 'wss://rpc-amoy.polygon.technology',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.Codex,
		url: 'https://rpc.codex.xyz',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Geth,
	},
	{
		chainId: ChainId.Codex,
		url: 'wss://rpc.codex.xyz',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.CodexTestnet,
		url: 'https://rpc.codex-stg.xyz',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Geth,
	},
	{
		chainId: ChainId.CodexTestnet,
		url: 'wss://rpc.codex-stg.xyz',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.SonicTestnet,
		url: 'https://rpc.testnet.soniclabs.com',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Other,
	},
	{
		chainId: ChainId.SonicTestnet,
		url: 'wss://rpc.testnet.soniclabs.com',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.WorldChainSepolia,
		url: 'https://worldchain-sepolia.g.alchemy.com/public',
		serviceProvider: ExecutionRpcProvider.Alchemy,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Reth,
	},
	{
		chainId: ChainId.WorldChainSepolia,
		url: 'wss://worldchain-sepolia.g.alchemy.com/public',
		serviceProvider: ExecutionRpcProvider.Alchemy,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.MonadTestnet,
		url: 'https://testnet-rpc.monad.xyz',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Other,
	},
	{
		chainId: ChainId.MonadTestnet,
		url: 'wss://testnet-rpc.monad.xyz',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.Plume,
		url: 'https://rpc.plume.org',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Other,
	},
	{
		chainId: ChainId.Plume,
		url: 'wss://rpc.plume.org',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.PlumeTestnet,
		url: 'https://testnet-rpc.plume.org',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Other,
	},
	{
		chainId: ChainId.PlumeTestnet,
		url: 'wss://testnet-rpc.plume.org',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.EthereumSepolia,
		url: 'https://ethereum-sepolia-rpc.publicnode.com',
		serviceProvider: ExecutionRpcProvider.PublicNode,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Geth,
	},
	{
		chainId: ChainId.EthereumSepolia,
		url: 'wss://ethereum-sepolia-rpc.publicnode.com',
		serviceProvider: ExecutionRpcProvider.PublicNode,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.OPSepolia,
		url: 'https://sepolia.optimism.io',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Reth,
	},
	{
		chainId: ChainId.OPSepolia,
		url: 'wss://sepolia.optimism.io',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.CeloSepolia,
		url: 'https://forno.celo-sepolia.celo-testnet.org',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Geth,
	},
	{
		chainId: ChainId.CeloSepolia,
		url: 'wss://forno.celo-sepolia.celo-testnet.org',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.UnichainSepolia,
		url: 'https://sepolia.unichain.org',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Unknown,
	},
	{
		chainId: ChainId.UnichainSepolia,
		url: 'wss://sepolia.unichain.org',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.WebSocket,
	},
	{
		chainId: ChainId.ArcTestnet,
		url: 'https://rpc.testnet.arc.network',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.Http,
		tevmForkTransportCompatible: true,
		executionClient: ExecutionClientId.Reth,
	},
	{
		chainId: ChainId.ArcTestnet,
		url: 'wss://rpc.testnet.arc.network',
		serviceProvider: ExecutionRpcProvider.NetworkDefault,
		transportType: TransportType.WebSocket,
	},
] as const satisfies readonly ExecutionEndpoint[]


// Lookups
export const executionEndpointsByChainId = Object.groupBy(
	executionEndpoints,
	(e) => e.chainId,
)
