import type { WalletMatrixScenario } from '../WalletCompatibilityMatrix.ts'
import {
	WalletHarnessConnectionProtocol,
	WalletHarnessEcosystem,
} from '../ecosystems.ts'


// Headed Connect / sign chrome is mapped through notification.html (see isRabbyNotificationPageUrl).
export const rabbyWalletMatrixScenarios = (version: string) => ([
	{
		id: 'rabby-create-new-1',
		wallet: {
			kind: 'rabby',
			version,
		},
		ecosystem: WalletHarnessEcosystem.Evm,
		initializationFlow: 'create-new',
		accountOrdinal: 1,
		connectionProtocol: WalletHarnessConnectionProtocol.Eip6963,
		connectionMethod: 'eth_requestAccounts',
		chain: 'eip155:31337',
		requestMethod: 'eth_requestAccounts',
		lifecycleEdgeCase: 'reject-retry-approve',
	},
	{
		id: 'rabby-create-new-2',
		wallet: {
			kind: 'rabby',
			version,
		},
		ecosystem: WalletHarnessEcosystem.Evm,
		initializationFlow: 'create-new',
		accountOrdinal: 2,
		connectionProtocol: WalletHarnessConnectionProtocol.Eip6963,
		connectionMethod: 'eth_requestAccounts',
		chain: 'eip155:31337',
		requestMethod: 'eth_requestAccounts',
		lifecycleEdgeCase: 'account-switch',
	},
	{
		id: 'rabby-watch-only-3',
		wallet: {
			kind: 'rabby',
			version,
		},
		ecosystem: WalletHarnessEcosystem.Evm,
		initializationFlow: 'watch-only',
		accountOrdinal: 3,
		connectionProtocol: WalletHarnessConnectionProtocol.Eip6963,
		connectionMethod: 'eth_requestAccounts',
		chain: 'eip155:31337',
		requestMethod: 'eth_accounts',
		lifecycleEdgeCase: 'account-visible',
	},
	{
		id: 'rabby-personal-sign-approve',
		wallet: {
			kind: 'rabby',
			version,
		},
		ecosystem: WalletHarnessEcosystem.Evm,
		initializationFlow: 'create-new',
		accountOrdinal: 1,
		connectionProtocol: WalletHarnessConnectionProtocol.Eip6963,
		connectionMethod: 'eth_requestAccounts',
		chain: 'eip155:31337',
		requestMethod: 'personal_sign',
		lifecycleEdgeCase: 'approve',
	},
	{
		id: 'rabby-personal-sign-reject',
		wallet: {
			kind: 'rabby',
			version,
		},
		ecosystem: WalletHarnessEcosystem.Evm,
		initializationFlow: 'create-new',
		accountOrdinal: 1,
		connectionProtocol: WalletHarnessConnectionProtocol.Eip6963,
		connectionMethod: 'eth_requestAccounts',
		chain: 'eip155:31337',
		requestMethod: 'personal_sign',
		lifecycleEdgeCase: 'reject',
	},
	{
		id: 'rabby-local-wallet_switchEthereumChain',
		wallet: {
			kind: 'rabby',
			version,
		},
		ecosystem: WalletHarnessEcosystem.Evm,
		initializationFlow: 'create-new',
		accountOrdinal: 1,
		connectionProtocol: WalletHarnessConnectionProtocol.Eip6963,
		connectionMethod: 'eth_requestAccounts',
		chain: 'eip155:31337',
		requestMethod: 'wallet_switchEthereumChain',
		lifecycleEdgeCase: 'loopback-rpc-only',
	},
	{
		id: 'rabby-local-eth_signTypedData_v4',
		wallet: {
			kind: 'rabby',
			version,
		},
		ecosystem: WalletHarnessEcosystem.Evm,
		initializationFlow: 'create-new',
		accountOrdinal: 1,
		connectionProtocol: WalletHarnessConnectionProtocol.Eip6963,
		connectionMethod: 'eth_requestAccounts',
		chain: 'eip155:31337',
		requestMethod: 'eth_signTypedData_v4',
		lifecycleEdgeCase: 'loopback-rpc-only',
	},
	{
		id: 'rabby-local-eth_sendTransaction',
		wallet: {
			kind: 'rabby',
			version,
		},
		ecosystem: WalletHarnessEcosystem.Evm,
		initializationFlow: 'create-new',
		accountOrdinal: 1,
		connectionProtocol: WalletHarnessConnectionProtocol.Eip6963,
		connectionMethod: 'eth_requestAccounts',
		chain: 'eip155:31337',
		requestMethod: 'eth_sendTransaction',
		lifecycleEdgeCase: 'loopback-rpc-only',
	},
	{
		id: 'rabby-disconnect-reload',
		wallet: {
			kind: 'rabby',
			version,
		},
		ecosystem: WalletHarnessEcosystem.Evm,
		initializationFlow: 'create-new',
		accountOrdinal: 1,
		connectionProtocol: WalletHarnessConnectionProtocol.Eip6963,
		connectionMethod: 'wallet_revokePermissions',
		chain: 'eip155:31337',
		requestMethod: 'eth_accounts',
		lifecycleEdgeCase: 'disconnect-reload',
	},
] as const satisfies readonly WalletMatrixScenario[])
