/* eslint-disable */
/* prettier-ignore */

export type introspection_types = {
    'AbiChanged': { kind: 'OBJECT'; name: 'AbiChanged'; fields: { 'blockNumber': { name: 'blockNumber'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'contentType': { name: 'contentType'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'BigInt'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'resolver': { name: 'resolver'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Resolver'; ofType: null; }; } }; 'transactionID': { name: 'transactionID'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Bytes'; ofType: null; }; } }; }; };
    'Account': { kind: 'OBJECT'; name: 'Account'; fields: { 'domains': { name: 'domains'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Domain'; ofType: null; }; }; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'registrations': { name: 'registrations'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Registration'; ofType: null; }; }; } }; 'wrappedDomains': { name: 'wrappedDomains'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'WrappedDomain'; ofType: null; }; }; } }; }; };
    'AddrChanged': { kind: 'OBJECT'; name: 'AddrChanged'; fields: { 'addr': { name: 'addr'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Account'; ofType: null; }; } }; 'blockNumber': { name: 'blockNumber'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'resolver': { name: 'resolver'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Resolver'; ofType: null; }; } }; 'transactionID': { name: 'transactionID'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Bytes'; ofType: null; }; } }; }; };
    'AuthorisationChanged': { kind: 'OBJECT'; name: 'AuthorisationChanged'; fields: { 'blockNumber': { name: 'blockNumber'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'isAuthorized': { name: 'isAuthorized'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'owner': { name: 'owner'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Bytes'; ofType: null; }; } }; 'resolver': { name: 'resolver'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Resolver'; ofType: null; }; } }; 'target': { name: 'target'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Bytes'; ofType: null; }; } }; 'transactionID': { name: 'transactionID'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Bytes'; ofType: null; }; } }; }; };
    'BigDecimal': unknown;
    'BigInt': unknown;
    'Boolean': unknown;
    'Bytes': unknown;
    'ContenthashChanged': { kind: 'OBJECT'; name: 'ContenthashChanged'; fields: { 'blockNumber': { name: 'blockNumber'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'hash': { name: 'hash'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Bytes'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'resolver': { name: 'resolver'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Resolver'; ofType: null; }; } }; 'transactionID': { name: 'transactionID'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Bytes'; ofType: null; }; } }; }; };
    'Domain': { kind: 'OBJECT'; name: 'Domain'; fields: { 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'BigInt'; ofType: null; }; } }; 'events': { name: 'events'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INTERFACE'; name: 'DomainEvent'; ofType: null; }; }; }; } }; 'expiryDate': { name: 'expiryDate'; type: { kind: 'SCALAR'; name: 'BigInt'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'isMigrated': { name: 'isMigrated'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'labelName': { name: 'labelName'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'labelhash': { name: 'labelhash'; type: { kind: 'SCALAR'; name: 'Bytes'; ofType: null; } }; 'name': { name: 'name'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'owner': { name: 'owner'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Account'; ofType: null; }; } }; 'parent': { name: 'parent'; type: { kind: 'OBJECT'; name: 'Domain'; ofType: null; } }; 'registrant': { name: 'registrant'; type: { kind: 'OBJECT'; name: 'Account'; ofType: null; } }; 'registration': { name: 'registration'; type: { kind: 'OBJECT'; name: 'Registration'; ofType: null; } }; 'resolvedAddress': { name: 'resolvedAddress'; type: { kind: 'OBJECT'; name: 'Account'; ofType: null; } }; 'resolver': { name: 'resolver'; type: { kind: 'OBJECT'; name: 'Resolver'; ofType: null; } }; 'subdomainCount': { name: 'subdomainCount'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'subdomains': { name: 'subdomains'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Domain'; ofType: null; }; }; }; } }; 'ttl': { name: 'ttl'; type: { kind: 'SCALAR'; name: 'BigInt'; ofType: null; } }; 'wrappedDomain': { name: 'wrappedDomain'; type: { kind: 'OBJECT'; name: 'WrappedDomain'; ofType: null; } }; 'wrappedOwner': { name: 'wrappedOwner'; type: { kind: 'OBJECT'; name: 'Account'; ofType: null; } }; }; };
    'DomainEvent': { kind: 'INTERFACE'; name: 'DomainEvent'; fields: { 'blockNumber': { name: 'blockNumber'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'domain': { name: 'domain'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Domain'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'transactionID': { name: 'transactionID'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Bytes'; ofType: null; }; } }; }; possibleTypes: 'ExpiryExtended' | 'FusesSet' | 'NameUnwrapped' | 'NameWrapped' | 'NewOwner' | 'NewResolver' | 'NewTTL' | 'Transfer' | 'WrappedTransfer'; };
    'Domain_filter': { kind: 'INPUT_OBJECT'; name: 'Domain_filter'; isOneOf: false; inputFields: [{ name: 'name'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'name_contains'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'name_not'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'owner'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }]; };
    'Domain_orderBy': { name: 'Domain_orderBy'; enumValues: 'createdAt' | 'expiryDate' | 'id' | 'labelName' | 'name'; };
    'ExpiryExtended': { kind: 'OBJECT'; name: 'ExpiryExtended'; fields: { 'blockNumber': { name: 'blockNumber'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'domain': { name: 'domain'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Domain'; ofType: null; }; } }; 'expiryDate': { name: 'expiryDate'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'BigInt'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'transactionID': { name: 'transactionID'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Bytes'; ofType: null; }; } }; }; };
    'FusesSet': { kind: 'OBJECT'; name: 'FusesSet'; fields: { 'blockNumber': { name: 'blockNumber'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'domain': { name: 'domain'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Domain'; ofType: null; }; } }; 'fuses': { name: 'fuses'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'transactionID': { name: 'transactionID'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Bytes'; ofType: null; }; } }; }; };
    'ID': unknown;
    'Int': unknown;
    'Int8': unknown;
    'InterfaceChanged': { kind: 'OBJECT'; name: 'InterfaceChanged'; fields: { 'blockNumber': { name: 'blockNumber'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'implementer': { name: 'implementer'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Bytes'; ofType: null; }; } }; 'interfaceID': { name: 'interfaceID'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Bytes'; ofType: null; }; } }; 'resolver': { name: 'resolver'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Resolver'; ofType: null; }; } }; 'transactionID': { name: 'transactionID'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Bytes'; ofType: null; }; } }; }; };
    'MulticoinAddrChanged': { kind: 'OBJECT'; name: 'MulticoinAddrChanged'; fields: { 'addr': { name: 'addr'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Bytes'; ofType: null; }; } }; 'blockNumber': { name: 'blockNumber'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'coinType': { name: 'coinType'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'BigInt'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'resolver': { name: 'resolver'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Resolver'; ofType: null; }; } }; 'transactionID': { name: 'transactionID'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Bytes'; ofType: null; }; } }; }; };
    'NameChanged': { kind: 'OBJECT'; name: 'NameChanged'; fields: { 'blockNumber': { name: 'blockNumber'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'resolver': { name: 'resolver'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Resolver'; ofType: null; }; } }; 'transactionID': { name: 'transactionID'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Bytes'; ofType: null; }; } }; }; };
    'NameRegistered': { kind: 'OBJECT'; name: 'NameRegistered'; fields: { 'blockNumber': { name: 'blockNumber'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'expiryDate': { name: 'expiryDate'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'BigInt'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'registrant': { name: 'registrant'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Account'; ofType: null; }; } }; 'registration': { name: 'registration'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Registration'; ofType: null; }; } }; 'transactionID': { name: 'transactionID'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Bytes'; ofType: null; }; } }; }; };
    'NameRenewed': { kind: 'OBJECT'; name: 'NameRenewed'; fields: { 'blockNumber': { name: 'blockNumber'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'expiryDate': { name: 'expiryDate'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'BigInt'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'registration': { name: 'registration'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Registration'; ofType: null; }; } }; 'transactionID': { name: 'transactionID'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Bytes'; ofType: null; }; } }; }; };
    'NameTransferred': { kind: 'OBJECT'; name: 'NameTransferred'; fields: { 'blockNumber': { name: 'blockNumber'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'newOwner': { name: 'newOwner'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Account'; ofType: null; }; } }; 'registration': { name: 'registration'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Registration'; ofType: null; }; } }; 'transactionID': { name: 'transactionID'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Bytes'; ofType: null; }; } }; }; };
    'NameUnwrapped': { kind: 'OBJECT'; name: 'NameUnwrapped'; fields: { 'blockNumber': { name: 'blockNumber'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'domain': { name: 'domain'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Domain'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'owner': { name: 'owner'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Account'; ofType: null; }; } }; 'transactionID': { name: 'transactionID'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Bytes'; ofType: null; }; } }; }; };
    'NameWrapped': { kind: 'OBJECT'; name: 'NameWrapped'; fields: { 'blockNumber': { name: 'blockNumber'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'domain': { name: 'domain'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Domain'; ofType: null; }; } }; 'expiryDate': { name: 'expiryDate'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'BigInt'; ofType: null; }; } }; 'fuses': { name: 'fuses'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'owner': { name: 'owner'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Account'; ofType: null; }; } }; 'transactionID': { name: 'transactionID'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Bytes'; ofType: null; }; } }; }; };
    'NewOwner': { kind: 'OBJECT'; name: 'NewOwner'; fields: { 'blockNumber': { name: 'blockNumber'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'domain': { name: 'domain'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Domain'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'owner': { name: 'owner'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Account'; ofType: null; }; } }; 'parentDomain': { name: 'parentDomain'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Domain'; ofType: null; }; } }; 'transactionID': { name: 'transactionID'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Bytes'; ofType: null; }; } }; }; };
    'NewResolver': { kind: 'OBJECT'; name: 'NewResolver'; fields: { 'blockNumber': { name: 'blockNumber'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'domain': { name: 'domain'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Domain'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'resolver': { name: 'resolver'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Resolver'; ofType: null; }; } }; 'transactionID': { name: 'transactionID'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Bytes'; ofType: null; }; } }; }; };
    'NewTTL': { kind: 'OBJECT'; name: 'NewTTL'; fields: { 'blockNumber': { name: 'blockNumber'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'domain': { name: 'domain'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Domain'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'transactionID': { name: 'transactionID'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Bytes'; ofType: null; }; } }; 'ttl': { name: 'ttl'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'BigInt'; ofType: null; }; } }; }; };
    'OrderDirection': { name: 'OrderDirection'; enumValues: 'asc' | 'desc'; };
    'PubkeyChanged': { kind: 'OBJECT'; name: 'PubkeyChanged'; fields: { 'blockNumber': { name: 'blockNumber'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'resolver': { name: 'resolver'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Resolver'; ofType: null; }; } }; 'transactionID': { name: 'transactionID'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Bytes'; ofType: null; }; } }; 'x': { name: 'x'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Bytes'; ofType: null; }; } }; 'y': { name: 'y'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Bytes'; ofType: null; }; } }; }; };
    'Query': { kind: 'OBJECT'; name: 'Query'; fields: { 'domains': { name: 'domains'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Domain'; ofType: null; }; }; }; } }; }; };
    'Registration': { kind: 'OBJECT'; name: 'Registration'; fields: { 'cost': { name: 'cost'; type: { kind: 'SCALAR'; name: 'BigInt'; ofType: null; } }; 'domain': { name: 'domain'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Domain'; ofType: null; }; } }; 'events': { name: 'events'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INTERFACE'; name: 'RegistrationEvent'; ofType: null; }; }; }; } }; 'expiryDate': { name: 'expiryDate'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'BigInt'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'labelName': { name: 'labelName'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'registrant': { name: 'registrant'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Account'; ofType: null; }; } }; 'registrationDate': { name: 'registrationDate'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'BigInt'; ofType: null; }; } }; }; };
    'RegistrationEvent': { kind: 'INTERFACE'; name: 'RegistrationEvent'; fields: { 'blockNumber': { name: 'blockNumber'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'registration': { name: 'registration'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Registration'; ofType: null; }; } }; 'transactionID': { name: 'transactionID'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Bytes'; ofType: null; }; } }; }; possibleTypes: 'NameRegistered' | 'NameRenewed' | 'NameTransferred'; };
    'Resolver': { kind: 'OBJECT'; name: 'Resolver'; fields: { 'addr': { name: 'addr'; type: { kind: 'OBJECT'; name: 'Account'; ofType: null; } }; 'address': { name: 'address'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Bytes'; ofType: null; }; } }; 'coinTypes': { name: 'coinTypes'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'BigInt'; ofType: null; }; }; } }; 'contentHash': { name: 'contentHash'; type: { kind: 'SCALAR'; name: 'Bytes'; ofType: null; } }; 'domain': { name: 'domain'; type: { kind: 'OBJECT'; name: 'Domain'; ofType: null; } }; 'events': { name: 'events'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INTERFACE'; name: 'ResolverEvent'; ofType: null; }; }; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'texts': { name: 'texts'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; } }; }; };
    'ResolverEvent': { kind: 'INTERFACE'; name: 'ResolverEvent'; fields: { 'blockNumber': { name: 'blockNumber'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'resolver': { name: 'resolver'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Resolver'; ofType: null; }; } }; 'transactionID': { name: 'transactionID'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Bytes'; ofType: null; }; } }; }; possibleTypes: 'AbiChanged' | 'AddrChanged' | 'AuthorisationChanged' | 'ContenthashChanged' | 'InterfaceChanged' | 'MulticoinAddrChanged' | 'NameChanged' | 'PubkeyChanged' | 'TextChanged' | 'VersionChanged'; };
    'String': unknown;
    'TextChanged': { kind: 'OBJECT'; name: 'TextChanged'; fields: { 'blockNumber': { name: 'blockNumber'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'key': { name: 'key'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'resolver': { name: 'resolver'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Resolver'; ofType: null; }; } }; 'transactionID': { name: 'transactionID'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Bytes'; ofType: null; }; } }; 'value': { name: 'value'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'Transfer': { kind: 'OBJECT'; name: 'Transfer'; fields: { 'blockNumber': { name: 'blockNumber'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'domain': { name: 'domain'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Domain'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'owner': { name: 'owner'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Account'; ofType: null; }; } }; 'transactionID': { name: 'transactionID'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Bytes'; ofType: null; }; } }; }; };
    'VersionChanged': { kind: 'OBJECT'; name: 'VersionChanged'; fields: { 'blockNumber': { name: 'blockNumber'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'resolver': { name: 'resolver'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Resolver'; ofType: null; }; } }; 'transactionID': { name: 'transactionID'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Bytes'; ofType: null; }; } }; 'version': { name: 'version'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'BigInt'; ofType: null; }; } }; }; };
    'WrappedDomain': { kind: 'OBJECT'; name: 'WrappedDomain'; fields: { 'domain': { name: 'domain'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Domain'; ofType: null; }; } }; 'expiryDate': { name: 'expiryDate'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'BigInt'; ofType: null; }; } }; 'fuses': { name: 'fuses'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'owner': { name: 'owner'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Account'; ofType: null; }; } }; }; };
    'WrappedTransfer': { kind: 'OBJECT'; name: 'WrappedTransfer'; fields: { 'blockNumber': { name: 'blockNumber'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'domain': { name: 'domain'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Domain'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'owner': { name: 'owner'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Account'; ofType: null; }; } }; 'transactionID': { name: 'transactionID'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Bytes'; ofType: null; }; } }; }; };
};

/** An IntrospectionQuery representation of your schema.
 *
 * @remarks
 * This is an introspection of your schema saved as a file by GraphQLSP.
 * It will automatically be used by `gql.tada` to infer the types of your GraphQL documents.
 * If you need to reuse this data or update your `scalars`, update `tadaOutputLocation` to
 * instead save to a .ts instead of a .d.ts file.
 */
export type introspection = {
  name: never;
  query: 'Query';
  mutation: never;
  subscription: never;
  types: introspection_types;
};

import * as gqlTada from 'gql.tada';

declare module 'gql.tada' {
  interface setupSchema {
    introspection: introspection
  }
}
