import type { Type } from 'arktype'

import type { SourceDefinition, SourcePublicEnv } from '$/sources/$Source.ts'

export type SourceOrigin = {
	origin: string
	/** Expected cross-origin `fetch` works without `/api-proxy` — must match what that provider’s HTTP client passes to `$/lib/http.ts` (`corsEnabled`). Also used for `/api-proxy` allow-list in `hooks.server.ts`. */
	corsEnabled: boolean
}

export type SourceProviderDefinition = {
	provider: SourceProvider
	label: string
	env?: Type<SourcePublicEnv>
	origins?: readonly SourceOrigin[]
	sources: readonly SourceDefinition[]
}

export enum SourceProvider {
	_Constants = '_Constants',
	Allium = 'Allium',
	Amboss = 'Amboss',
	AtprotoBsky = 'AtprotoBsky',
	AtprotoBskySocial = 'AtprotoBskySocial',
	Beacon = 'Beacon',
	BeaconchaIn = 'BeaconchaIn',
	Bittensor = 'Bittensor',
	Blobscan = 'Blobscan',
	BitcoinBips = 'BitcoinBips',
	BitcoinCashBcmr = 'BitcoinCashBcmr',
	BitcoinCashChips = 'BitcoinCashChips',
	BitcoinCashNode = 'BitcoinCashNode',
	BitcoinCore = 'BitcoinCore',
	Blockchair = 'Blockchair',
	Blockscout = 'Blockscout',
	Caips = 'Caips',
	Chainlist = 'Chainlist',
	Coingecko = 'Coingecko',
	CoinMarketCap = 'CoinMarketCap',
	Coinpaprika = 'Coinpaprika',
	CometBft = 'CometBft',
	CosmosChainRegistry = 'CosmosChainRegistry',
	CosmosAdrs = 'CosmosAdrs',
	CosmosSdk = 'CosmosSdk',
	Defillama = 'Defillama',
	Dexscreener = 'Dexscreener',
	Eip8004Scan = 'Eip8004Scan',
	Dune = 'Dune',
	DogecoinDips = 'DogecoinDips',
	DogecoinCore = 'DogecoinCore',
	Ensips = 'Ensips',
	EthereumEips = 'EthereumEips',
	EthereumLists = 'EthereumLists',
	EthereumSpecs = 'EthereumSpecs',
	Etherscan = 'Etherscan',
	Esplora = 'Esplora',
	Farcaster = 'Farcaster',
	Fedi = 'Fedi',
	FilecoinFips = 'FilecoinFips',
	Filfox = 'Filfox',
	FxEmbed = 'FxEmbed',
	Helius = 'Helius',
	Hyperliquid = 'Hyperliquid',
	HyperliquidDocs = 'HyperliquidDocs',
	Ipfs = 'Ipfs',
	L2Beat = 'L2Beat',
	Lens = 'Lens',
	Hey = 'Hey',
	Lifi = 'Lifi',
	LitecoinCore = 'LitecoinCore',
	LitecoinLips = 'LitecoinLips',
	LightningLnd = 'LightningLnd',
	LightningMempoolSpace = 'LightningMempoolSpace',
	Local = 'Local',
	LogosDocs = 'LogosDocs',
	Lotus = 'Lotus',
	Mastodon = 'Mastodon',
	MetadataVision = 'MetadataVision',
	MevRelay = 'MevRelay',
	MempoolSpace = 'MempoolSpace',
	NearBlocks = 'NearBlocks',
	NearNeps = 'NearNeps',
	NearRpc = 'NearRpc',
	Neynar = 'Neynar',
	MoneroDaemonRpc = 'MoneroDaemonRpc',
	NostrBand = 'NostrBand',
	Openchain = 'Openchain',
	Polkadot = 'Polkadot',
	PolkadotRfcs = 'PolkadotRfcs',
	Piped = 'Piped',
	Primal = 'Primal',
	QuilibriumNodeRpc = 'QuilibriumNodeRpc',
	QuilibriumDocs = 'QuilibriumDocs',
	Reddit = 'Reddit',
	RedditPublic = 'RedditPublic',
	Rss = 'Rss',
	Rss2Json = 'Rss2Json',
	Snapchain = 'Snapchain',
	Solana = 'Solana',
	SolanaSimds = 'SolanaSimds',
	Sourcify = 'Sourcify',
	Subscan = 'Subscan',
	SubstrateSidecar = 'SubstrateSidecar',
	Superchain = 'Superchain',
	Swarm = 'Swarm',
	TheGraph = 'TheGraph',
	ThreeXpl = 'ThreeXpl',
	TradingView = 'TradingView',
	TronFullNode = 'TronFullNode',
	TronGrid = 'TronGrid',
	TronScan = 'TronScan',
	TronSolidityNode = 'TronSolidityNode',
	TrustWalletAssets = 'TrustWalletAssets',
	Voltaire = 'Voltaire',
	X = 'X',
	Youtube = 'Youtube',
	ZcashZips = 'ZcashZips',
	Zcashd = 'Zcashd',
	Zebra = 'Zebra',
	ZeroG = 'ZeroG',
}
