export enum Source {
	_User = '_User',
	_Constants = '_Constants',
	Allium = 'Allium',
	NetworkDefault = 'NetworkDefault',
	ChainList = 'ChainList',
	Coingecko = 'Coingecko',
	CoinMarketCap = 'CoinMarketCap',
	Coinpaprika = 'Coinpaprika',
	Dexscreener = 'Dexscreener',
	Defillama = 'Defillama',
	Dune = 'Dune',
	Scan8004 = 'Scan8004',
	Eips = 'Eips',
	Caips = 'Caips',
	Ensips = 'Ensips',
	LiFi = 'LiFi',
	NearIntents = 'NearIntents',
	Openchain = 'Openchain',
	Sourcify = 'Sourcify',
	Neynar = 'Neynar',
	TheGraph = 'TheGraph',
	Uniswap = 'Uniswap',
	Farcaster = 'Farcaster',
	Snapchain = 'Snapchain',
	Blockscout = 'Blockscout',
	Voltaire = 'Voltaire',
}
