import type { Type } from 'arktype'

import type { SourceProvider } from '$/sources/$SourceProvider.ts'

/** String-keyed map of public env (matches `$env/dynamic/public` after coercing missing values to `''`). */
export type SourcePublicEnv = Record<string, string>

export enum Source {
	Allium_Rest = 'Allium_Rest',
	Atproto_Xrpc = 'Atproto_Xrpc',
	Atproto_BskySocial_Xrpc = 'Atproto_BskySocial_Xrpc',
	Beacon_Rest = 'Beacon_Rest',
	BitcoinBips_Github = 'BitcoinBips_Github',
	BitcoinCashBcmr_Github = 'BitcoinCashBcmr_Github',
	BitcoinCashChips_Gitlab = 'BitcoinCashChips_Gitlab',
	BitcoinCashNode_JsonRpc = 'BitcoinCashNode_JsonRpc',
	BitcoinCore_JsonRpc = 'BitcoinCore_JsonRpc',
	Blockchair_Rest = 'Blockchair_Rest',
	Blobscan_Rest = 'Blobscan_Rest',
	Blockscout_Rest = 'Blockscout_Rest',
	Caips_Github = 'Caips_Github',
	CaipNamespaces_Github = 'CaipNamespaces_Github',
	Chainlist_Rest = 'Chainlist_Rest',
	Coingecko_OpenApi = 'Coingecko_OpenApi',
	Coingecko_Rest = 'Coingecko_Rest',
	CoinMarketCap_Rest = 'CoinMarketCap_Rest',
	Coinpaprika_OpenApi = 'Coinpaprika_OpenApi',
	CometBft_Rest = 'CometBft_Rest',
	Constants_Internal = 'Constants_Internal',
	CosmosChainRegistry_Github = 'CosmosChainRegistry_Github',
	CosmosAdrs_Github = 'CosmosAdrs_Github',
	CosmosSdk_Rest = 'CosmosSdk_Rest',
	Defillama_OpenApi = 'Defillama_OpenApi',
	Defillama_Rest = 'Defillama_Rest',
	Dexscreener_OpenApi = 'Dexscreener_OpenApi',
	Eip8004Scan_Rest = 'Eip8004Scan_Rest',
	Dune_Rest = 'Dune_Rest',
	DogecoinDips_Github = 'DogecoinDips_Github',
	DogecoinCore_JsonRpc = 'DogecoinCore_JsonRpc',
	Ensips_Github = 'Ensips_Github',
	EthereumEips_Github = 'EthereumEips_Github',
	EthereumLists_Rest = 'EthereumLists_Rest',
	EthereumSpecs_Github = 'EthereumSpecs_Github',
	Etherscan_Rest = 'Etherscan_Rest',
	Esplora_Rest = 'Esplora_Rest',
	Farcaster_Rest = 'Farcaster_Rest',
	Fedi_Rest = 'Fedi_Rest',
	FilecoinFips_Github = 'FilecoinFips_Github',
	Filfox_Rest = 'Filfox_Rest',
	Helius_Rest = 'Helius_Rest',
	Hyperliquid_JsonRpc = 'Hyperliquid_JsonRpc',
	HyperliquidDocs_Rest = 'HyperliquidDocs_Rest',
	Hyperliquid_Rest = 'Hyperliquid_Rest',
	Ipfs_Rest = 'Ipfs_Rest',
	L2Beat_Rest = 'L2Beat_Rest',
	Lens_Graphql = 'Lens_Graphql',
	Lens_HeyGraphql = 'Lens_HeyGraphql',
	Lifi_Rest = 'Lifi_Rest',
	LitecoinCore_JsonRpc = 'LitecoinCore_JsonRpc',
	LitecoinLips_Github = 'LitecoinLips_Github',
	LightningLnd_Rest = 'LightningLnd_Rest',
	LightningMempoolSpace_Rest = 'LightningMempoolSpace_Rest',
	Local_Internal = 'Local_Internal',
	LogosDocs_Rest = 'LogosDocs_Rest',
	Lotus_JsonRpc = 'Lotus_JsonRpc',
	Mastodon_Rest = 'Mastodon_Rest',
	MetadataVision_Rest = 'MetadataVision_Rest',
	MevRelay_Rest = 'MevRelay_Rest',
	MempoolSpace_Rest = 'MempoolSpace_Rest',
	MoneroDaemonRpc_JsonRpc = 'MoneroDaemonRpc_JsonRpc',
	NearRpc_JsonRpc = 'NearRpc_JsonRpc',
	NearNeps_Github = 'NearNeps_Github',
	Neynar_Rest = 'Neynar_Rest',
	NostrBand_Rest = 'NostrBand_Rest',
	Openchain_Rest = 'Openchain_Rest',
	Polkadot_JsonRpc = 'Polkadot_JsonRpc',
	PolkadotRfcs_Github = 'PolkadotRfcs_Github',
	Piped_Rest = 'Piped_Rest',
	Primal_Rest = 'Primal_Rest',
	QuilibriumNodeRpc_Grpc = 'QuilibriumNodeRpc_Grpc',
	QuilibriumDocs_Rest = 'QuilibriumDocs_Rest',
	Reddit_Rest = 'Reddit_Rest',
	Reddit_PublicJson = 'Reddit_PublicJson',
	Rss_Rest = 'Rss_Rest',
	Rss2Json_Rest = 'Rss2Json_Rest',
	Snapchain_Rest = 'Snapchain_Rest',
	Solana_JsonRpc = 'Solana_JsonRpc',
	SolanaSimds_Github = 'SolanaSimds_Github',
	Sourcify_Rest = 'Sourcify_Rest',
	Subscan_Rest = 'Subscan_Rest',
	SubstrateSidecar_Rest = 'SubstrateSidecar_Rest',
	Superchain_Github = 'Superchain_Github',
	Swarm_Rest = 'Swarm_Rest',
	TheGraph_Graphql = 'TheGraph_Graphql',
	ThreeXpl_Rest = 'ThreeXpl_Rest',
	TradingView_Rest = 'TradingView_Rest',
	TronFullNode_Rest = 'TronFullNode_Rest',
	TronGrid_Rest = 'TronGrid_Rest',
	TronScan_Rest = 'TronScan_Rest',
	TronSolidityNode_Rest = 'TronSolidityNode_Rest',
	Voltaire_JsonRpc = 'Voltaire_JsonRpc',
	X_FxEmbed_Rest = 'X_FxEmbed_Rest',
	X_Rest = 'X_Rest',
	Youtube_Rest = 'Youtube_Rest',
	ZcashZips_Github = 'ZcashZips_Github',
	Zcashd_JsonRpc = 'Zcashd_JsonRpc',
	Zebra_JsonRpc = 'Zebra_JsonRpc',
	ZeroGChain_JsonRpc = 'ZeroGChain_JsonRpc',
	ZeroGChainScan_Rest = 'ZeroGChainScan_Rest',
	ZeroGDaNode_Grpc = 'ZeroGDaNode_Grpc',
	ZeroGDocs_Rest = 'ZeroGDocs_Rest',
	ZeroGStorageNode_JsonRpc = 'ZeroGStorageNode_JsonRpc',
	ZeroGStorageScan_Rest = 'ZeroGStorageScan_Rest',
}

export type SourceDefinition = {
	provider: SourceProvider
	source: Source
	label: string
	env?: Type<SourcePublicEnv>
}
