// Generated from APP.ts. Do not edit by hand.

import type { SourceDefinition, SourceProviderDefinition as SourceProviderDefinitionTemplate, SourcePublicEnv } from '$/sources/$sources.ts'
import type { Source } from '$/sources/Source.ts'
import type { SourceBinding } from '$/sources/SourceBinding.ts'
import type { Type } from 'arktype'

export type SourceOrigin = {
	origin: string
	corsEnabled: boolean
}

export type SourceProviderDefinition = SourceProviderDefinitionTemplate<SourceProvider, Source> & {
	env?: Type<SourcePublicEnv>
	sources: readonly SourceDefinition<SourceProvider, Source>[]
	bindings: readonly SourceBinding[]
}

export enum SourceProvider {
	_Constants = '_Constants',
	Local = 'Local',
	AtprotoBsky = 'AtprotoBsky',
	AtprotoBskySocial = 'AtprotoBskySocial',
	AtprotoSync = 'AtprotoSync',
	Allium = 'Allium',
	Amboss = 'Amboss',
	BetterCallDev = 'BetterCallDev',
	Beacon = 'Beacon',
	BeaconchaIn = 'BeaconchaIn',
	BitcoinBips = 'BitcoinBips',
	BitcoinCashBcmr = 'BitcoinCashBcmr',
	BitcoinCashChips = 'BitcoinCashChips',
	BitcoinCashNode = 'BitcoinCashNode',
	BitcoinCore = 'BitcoinCore',
	Bittensor = 'Bittensor',
	Blockchair = 'Blockchair',
	Blockscout = 'Blockscout',
	Blobscan = 'Blobscan',
	Caips = 'Caips',
	Chainlist = 'Chainlist',
	Cashu = 'Cashu',
	Coingecko = 'Coingecko',
	CoinMarketCap = 'CoinMarketCap',
	Coinpaprika = 'Coinpaprika',
	CometBft = 'CometBft',
	CosmosAdrs = 'CosmosAdrs',
	CosmosChainRegistry = 'CosmosChainRegistry',
	CosmosSdk = 'CosmosSdk',
	Defillama = 'Defillama',
	Dexscreener = 'Dexscreener',
	DogecoinDips = 'DogecoinDips',
	Dune = 'Dune',
	DogecoinCore = 'DogecoinCore',
	Ensips = 'Ensips',
	Eip8004Scan = 'Eip8004Scan',
	Esplora = 'Esplora',
	EthereumLists = 'EthereumLists',
	EthereumEips = 'EthereumEips',
	EthereumSpecs = 'EthereumSpecs',
	Etherscan = 'Etherscan',
	Filfox = 'Filfox',
	FilecoinFips = 'FilecoinFips',
	Helius = 'Helius',
	FxEmbed = 'FxEmbed',
	Farcaster = 'Farcaster',
	Hyperliquid = 'Hyperliquid',
	HyperliquidDocs = 'HyperliquidDocs',
	Ipfs = 'Ipfs',
	L2Beat = 'L2Beat',
	LightningLnd = 'LightningLnd',
	LightningMempoolSpace = 'LightningMempoolSpace',
	LitecoinCore = 'LitecoinCore',
	MempoolSpace = 'MempoolSpace',
	MetadataVision = 'MetadataVision',
	Lifi = 'Lifi',
	Lotus = 'Lotus',
	LogosDocs = 'LogosDocs',
	Lens = 'Lens',
	MevRelay = 'MevRelay',
	MoneroDaemonRpc = 'MoneroDaemonRpc',
	NearBlocks = 'NearBlocks',
	LitecoinLips = 'LitecoinLips',
	NearNeps = 'NearNeps',
	NearRpc = 'NearRpc',
	Neynar = 'Neynar',
	NostrBand = 'NostrBand',
	Mastodon = 'Mastodon',
	Fedi = 'Fedi',
	NostrRelay = 'NostrRelay',
	Openchain = 'Openchain',
	Payjoin = 'Payjoin',
	Piped = 'Piped',
	Polkadot = 'Polkadot',
	Primal = 'Primal',
	PolkadotRfcs = 'PolkadotRfcs',
	QuilibriumDocs = 'QuilibriumDocs',
	QuilibriumNodeRpc = 'QuilibriumNodeRpc',
	Reddit = 'Reddit',
	RedditPublic = 'RedditPublic',
	Rss = 'Rss',
	Rss2Json = 'Rss2Json',
	Superchain = 'Superchain',
	Solana = 'Solana',
	SolanaSimds = 'SolanaSimds',
	Snapchain = 'Snapchain',
	Sourcify = 'Sourcify',
	Subscan = 'Subscan',
	SubstrateSidecar = 'SubstrateSidecar',
	Swarm = 'Swarm',
	TezosDappetizer = 'TezosDappetizer',
	TezosNode = 'TezosNode',
	TheGraph = 'TheGraph',
	ThreeXpl = 'ThreeXpl',
	TradingView = 'TradingView',
	TronFullNode = 'TronFullNode',
	TronGrid = 'TronGrid',
	TronScan = 'TronScan',
	TronSolidityNode = 'TronSolidityNode',
	TrustWalletAssets = 'TrustWalletAssets',
	Tzkt = 'Tzkt',
	Voltaire = 'Voltaire',
	ZeroG = 'ZeroG',
	X = 'X',
	Youtube = 'Youtube',
	Zcashd = 'Zcashd',
	ZcashZips = 'ZcashZips',
	Zebra = 'Zebra',
}
