import { Source } from '$/sources/Source.ts'
import {
	EntityFieldType,
	EntityFieldCardinality,
	type EntityDefinition,
	type EntityFieldDefinition,
} from '$/schema/$schema.ts'
import { EntityType } from '$/schema/EntityType.ts'
import { type } from 'arktype'

export enum _GlobalSelector {
	Scope = 'scope',
}

export default {
	entityType: EntityType._Global,

	label: 'Global',
	labelPlural: 'Globals',

	selectors: [
		{
			name: _GlobalSelector.Scope,
			fields: ['scope'],
		},
	],

	fields: [
		{
			name: 'scope',
			type: EntityFieldType.Primitive,
			primitiveType: type('string'),
			cardinality: EntityFieldCardinality.One,
		},
		{
			name: '$$networks',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.Network,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Constants_Internal],
		},
		{
			name: '$$evmNetworks',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.EvmNetwork,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Chainlist_Rest, Source.EthereumLists_Rest],
		},
		{
			name: '$$networkUpgrades',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.EthereumNetworkUpgrade,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Constants_Internal],
		},
		{
			name: '$$proposals',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.SpecificationProposal,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [
				Source.BitcoinBips_Github,
				Source.BitcoinCashChips_Gitlab,
				Source.EthereumEips_Github,
				Source.Ensips_Github,
				Source.Caips_Github,
				Source.CosmosAdrs_Github,
				Source.DogecoinDips_Github,
				Source.FilecoinFips_Github,
				Source.HyperliquidDocs_Rest,
				Source.LitecoinLips_Github,
				Source.NearNeps_Github,
				Source.PolkadotRfcs_Github,
				Source.QuilibriumDocs_Rest,
				Source.SolanaSimds_Github,
				Source.ZcashZips_Github,
			],
		},
		{
			name: '$$specificationRealms',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.SpecificationRealm,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Constants_Internal],
		},
		{
			name: '$$proposalKinds',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.SpecificationProposalKind,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Constants_Internal],
		},
		{
			name: '$$coins',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.Coin,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [
				Source.Constants_Internal,
				Source.Coingecko_Rest,
				Source.CoinMarketCap_Rest,
				Source.Coinpaprika_OpenApi,
			],
		},
		{
			name: '$$markets',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.Market,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [
				Source.Constants_Internal,
				Source.Coingecko_Rest,
				Source.Coingecko_OpenApi,
				Source.CoinMarketCap_Rest,
				Source.Coinpaprika_OpenApi,
				Source.Defillama_OpenApi,
				Source.TradingView_Rest,
			],
		},
		{
			name: '$$marketVenues',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.MarketVenue,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Constants_Internal],
		},
		{
			name: '$$currencies',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.Currency,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Constants_Internal],
		},
		{
			name: '$$marketPrices',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.MarketPrice,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [
				Source.Constants_Internal,
				Source.Coingecko_Rest,
				Source.Coingecko_OpenApi,
				Source.CoinMarketCap_Rest,
				Source.Coinpaprika_OpenApi,
				Source.Defillama_OpenApi,
				Source.TradingView_Rest,
			],
		},
		{
			name: '$$marketTimeIntervalTimestamps',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.Market_TimeInterval_Timestamp,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [
				Source.Constants_Internal,
			],
		},
		{
			name: '$$actors',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.EvmAccount,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Local_Internal],
		},
		{
			name: '$$xmtpConversations',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.XmtpConversation,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Local_Internal],
		},
		{
			name: '$$vaults',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.Vault,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Constants_Internal],
		},
		{
			name: '$$blockheadSources',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.BlockheadSource,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Local_Internal],
		},
		{
			name: '$$blockheadWallets',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.BlockheadWallet,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Local_Internal],
		},
		{
			name: '$$blockheadWalletConnections',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.BlockheadWalletConnection,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Local_Internal],
		},
		{
			name: '$$blockheadWalletAccounts',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.BlockheadWalletAccount,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Local_Internal],
		},
		{
			name: '$$blockheadSessions',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.BlockheadSession,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Local_Internal],
		},
		{
			name: '$$blockheadPanelTrees',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.BlockheadPanelTree,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Local_Internal],
		},
		{
			name: '$$blockheadFarcasterAccountConnections',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.BlockheadFarcasterAccountConnection,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Local_Internal],
		},
		{
			name: '$$blockheadAgentConversations',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.BlockheadAgentConversation,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Local_Internal],
		},
		{
			name: '$$eip8004Services',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.EvmNft,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Eip8004Scan_Rest],
		},
		{
			name: '$$bridgeTransactions',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.BridgeTransaction,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Local_Internal],
		},
		{
			name: '$$blockheadRoomPeers',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.BlockheadRoomPeer,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Local_Internal],
		},
		{
			name: '$$blockheadRooms',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.BlockheadRoom,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Local_Internal],
		},
		{
			name: '$$stateChannels',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.StateChannel,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Local_Internal],
		},
		{
			name: '$$liquidityPositions',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.LiquidityPosition,
			cardinality: EntityFieldCardinality.Many,
		},
		{
			name: '$$liquidityPools',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.LiquidityPool,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Dexscreener_OpenApi],
		},
		{
			name: '$$blockheadSharedAddresses',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.BlockheadSharedAddress,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Local_Internal],
		},
		{
			name: '$$actorCoins',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.EvmNetworkActorCoinBalance,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Allium_Rest],
		},
		{
			name: 'duneCreditsUsed',
			type: EntityFieldType.Primitive,
			primitiveType: type('number'),
			cardinality: EntityFieldCardinality.ZeroOrOne,
			defaultSources: [Source.Dune_Rest],
		},
		{
			name: 'duneCreditsIncluded',
			type: EntityFieldType.Primitive,
			primitiveType: type('number'),
			cardinality: EntityFieldCardinality.ZeroOrOne,
			defaultSources: [Source.Dune_Rest],
		},
	] as const satisfies readonly EntityFieldDefinition[],
} as const satisfies EntityDefinition
