// Generated from APP.ts. Do not edit by hand.

import { EntityFieldCardinality, EntityFieldType, type EntityDefinition } from '$/schema/$schema.ts'
import { EntityType } from '$/schema/EntityType.ts'
import { type } from 'arktype'

export enum _GlobalSelector {
	Scope = 'Scope',
}
export default {
	entityType: EntityType._Global,
	label: 'global',
	labelPlural: 'globals',
	description: 'Root catalog and navigation scope for top-level networks, assets, markets, proposals, and local Blockhead state.',
	selectors: [
		{
			name: _GlobalSelector.Scope,
			fields: [
				'scope',
			],
		},
	],
	fields: [
		{
				name: 'scope',
				label: 'Scope',
				description: 'The fixed scope value that identifies this hub row.',
				type: EntityFieldType.Primitive,
				primitiveType: type('string'),
				cardinality: EntityFieldCardinality.One,
		},
		{
				name: '$$networks',
				label: 'networks',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.Network,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$evmNetworks',
				label: 'EVM networks',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.EvmNetwork,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$networkUpgrades',
				label: 'network upgrades',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.EthereumNetworkUpgrade,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$proposals',
				label: 'proposals',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.SpecificationProposal,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$specificationRealms',
				label: 'specification realms',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.SpecificationRealm,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$proposalKinds',
				label: 'proposal kinds',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.SpecificationProposalKind,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$coins',
				label: 'coins',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.Coin,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$markets',
				label: 'markets',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.Market,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$marketVenues',
				label: 'market venues',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.MarketVenue,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$currencies',
				label: 'currencies',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.Currency,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$marketPrices',
				label: 'market prices',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.MarketPrice,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$marketTimeIntervalTimestamps',
				label: 'market time interval timestamps',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.Market_TimeInterval_Timestamp,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$actors',
				label: 'actors',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.EvmAccount,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$xmtpConversations',
				label: 'XMTP conversations',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.XmtpConversation,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$blockheadSources',
				label: 'blockhead sources',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.BlockheadSource,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$blockheadWallets',
				label: 'blockhead wallets',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.BlockheadWallet,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$blockheadWalletConnections',
				label: 'blockhead wallet connections',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.BlockheadWalletConnection,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$blockheadWalletAccounts',
				label: 'blockhead wallet accounts',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.BlockheadWalletAccount,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$blockheadWalletTransportSessions',
				label: 'blockhead wallet transport sessions',
				type: EntityFieldType.EntitiesReference,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$blockheadWalletRequests',
				label: 'blockhead wallet requests',
				type: EntityFieldType.EntitiesReference,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$blockheadWalletCapabilityGrants',
				label: 'blockhead wallet capability grants',
				type: EntityFieldType.EntitiesReference,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$blockheadWalletAuthentications',
				label: 'blockhead wallet authentications',
				type: EntityFieldType.EntitiesReference,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$blockheadSessions',
				label: 'blockhead sessions',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.BlockheadSession,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$blockheadPanelTrees',
				label: 'blockhead panel trees',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.BlockheadPanelTree,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$blockheadFarcasterAccountConnections',
				label: 'blockhead Farcaster account connections',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.BlockheadFarcasterAccountConnection,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$blockheadAgentConversations',
				label: 'blockhead agent conversations',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.BlockheadAgentConversation,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$aiModelCatalogs',
				label: 'AI model catalogs',
				type: EntityFieldType.EntitiesReference,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$aiArtifactCatalogs',
				label: 'AI artifact catalogs',
				type: EntityFieldType.EntitiesReference,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$agentNetworks',
				label: 'agent networks',
				type: EntityFieldType.EntitiesReference,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$blockheadAlgorandParticipationKeys',
				label: 'blockhead algorand participation keys',
				type: EntityFieldType.EntitiesReference,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$bridgeTransactions',
				label: 'bridge transactions',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.BlockheadBridgeTransaction,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$bridgeTransfers',
				label: 'bridge transfers',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.BridgeTransfer,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$eip8004Services',
				label: 'eip8004 services',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.EvmNft,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$blockheadRoomPeers',
				label: 'blockhead room peers',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.BlockheadRoomPeer,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$blockheadRooms',
				label: 'blockhead rooms',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.BlockheadRoom,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$blockheadStateChannels',
				label: 'blockhead state channels',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.BlockheadStateChannel,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$liquidityPositions',
				label: 'liquidity positions',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.LiquidityPosition,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$liquidityPools',
				label: 'liquidity pools',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.LiquidityPool,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$blockheadSharedAddresses',
				label: 'blockhead shared addresses',
				type: EntityFieldType.EntitiesReference,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$blockheadZeroGStorageNodeStates',
				label: 'blockhead zero g storage node states',
				type: EntityFieldType.EntitiesReference,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$blockheadZeroGStoredChunks',
				label: 'blockhead zero g stored chunks',
				type: EntityFieldType.EntitiesReference,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$blockheadZeroGStorageProofs',
				label: 'blockhead zero g storage proofs',
				type: EntityFieldType.EntitiesReference,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$actorCoins',
				label: 'actor coins',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.EvmNetworkActorCoinBalance,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: 'duneCreditsUsed',
				label: 'dune credits used',
				type: EntityFieldType.Primitive,
				primitiveType: type('number'),
				cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
				name: 'duneCreditsIncluded',
				label: 'dune credits included',
				type: EntityFieldType.Primitive,
				primitiveType: type('number'),
				cardinality: EntityFieldCardinality.ZeroOrOne,
		},
	],
} as const satisfies EntityDefinition
