import { Source } from '$/sources/$Source.ts'
import {
	EntityFieldType,
	EntityFieldCardinality,
	type EntityDefinition,
	type EntityFieldDefinition,
} from '$/schema/$EntityDefinition.ts'
import { EntityType } from '$/schema/$EntityType.ts'
import { type } from 'arktype'

export default {
	entityType: EntityType._Global,

	label: 'Global',
	labelPlural: 'Globals',

	id: type({}),

	fields: [
		{
			name: '$$networks',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.Network,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Chainlist_Rest, Source.EthereumLists_Rest],
		},
		{
			name: '$$networkUpgrades',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.NetworkUpgrade,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Constants_Internal],
		},
		{
			name: '$$proposals',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.Proposal,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [
				Source.EthereumEips_Github,
				Source.Ensips_Github,
				Source.Caips_Github,
			],
		},
		{
			name: '$$proposalRealms',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.ProposalRealm,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Constants_Internal],
		},
		{
			name: '$$proposalKinds',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.ProposalKind,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Constants_Internal],
		},
		{
			name: '$$coins',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.Coin,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [
				Source.Constants_Internal,
				Source.Coingecko_Rest,
				Source.CoinMarketCap_Rest,
				Source.Coinpaprika_OpenApi,
			],
		},
		{
			name: '$$markets',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.Market,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [
				Source.Constants_Internal,
				Source.Coingecko_Rest,
				Source.Coingecko_OpenApi,
				Source.CoinMarketCap_Rest,
				Source.Coinpaprika_OpenApi,
				Source.Defillama_OpenApi,
				Source.TradingView_Rest,
			],
		},
		{
			name: '$$marketVenues',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.MarketVenue,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Constants_Internal],
		},
		{
			name: '$$currencies',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.Currency,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Constants_Internal],
		},
		{
			name: '$$marketPrices',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.MarketPrice,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [
				Source.Constants_Internal,
				Source.Coingecko_Rest,
				Source.Coingecko_OpenApi,
				Source.CoinMarketCap_Rest,
				Source.Coinpaprika_OpenApi,
				Source.Defillama_OpenApi,
				Source.TradingView_Rest,
			],
		},
		{
			name: '$$marketTimeIntervalTimestamps',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.Market_TimeInterval_Timestamp,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [
				Source.Coingecko_Rest,
				Source.Coingecko_OpenApi,
				Source.Defillama_OpenApi,
				Source.Coinpaprika_OpenApi,
				Source.CoinMarketCap_Rest,
			],
		},
		{
			name: '$$evmTopics',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.EvmTopic,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Local_Internal],
		},
		{
			name: '$$evmSelectors',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.EvmSelector,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Local_Internal],
		},
		{
			name: '$$evmErrors',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.EvmError,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Local_Internal],
		},
		{
			name: '$$actors',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.Actor,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Local_Internal],
		},
		{
			name: '$$xmtpConversations',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.XmtpConversation,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Local_Internal],
		},
		{
			name: '$$vaults',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.Vault,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Dexscreener_OpenApi],
		},
		{
			name: '$$blockheadSources',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.BlockheadSource,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Local_Internal],
		},
		{
			name: '$$blockheadSessions',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.BlockheadSession,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Local_Internal],
		},
		{
			name: '$$blockheadPanelTrees',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.BlockheadPanelTree,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Local_Internal],
		},
		{
			name: '$$blockheadFarcasterAccountConnections',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.BlockheadFarcasterAccountConnection,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Local_Internal],
		},
		{
			name: '$$blockheadAgentConversations',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.BlockheadAgentConversation,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Local_Internal],
		},
		{
			name: '$$eip8004Services',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.Eip8004Service,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Constants_Internal],
		},
		{
			name: '$$bridgeTransactions',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.BridgeTransaction,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Local_Internal],
		},
		{
			name: '$$blockheadRoomPeers',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.BlockheadRoomPeer,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Local_Internal],
		},
		{
			name: '$$blockheadRooms',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.BlockheadRoom,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Local_Internal],
		},
		{
			name: '$$stateChannels',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.StateChannel,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Local_Internal],
		},
		{
			name: '$$liquidityPositions',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.LiquidityPosition,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Constants_Internal],
		},
		{
			name: '$$liquidityPools',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.LiquidityPool,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Dexscreener_OpenApi],
		},
		{
			name: '$$blockheadSharedAddresses',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.BlockheadSharedAddress,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Local_Internal],
		},
		{
			name: '$$actorCoins',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.ActorCoin,
			cardinality: EntityFieldCardinality.Many,
			defaultSources: [Source.Allium_Rest],
		},
		{
			name: 'duneCreditsUsed',
			type: EntityFieldType.Primitive,
			primitiveType: type('number'),
			cardinality: EntityFieldCardinality.ZeroOrOne,
			defaultSources: [Source.Dune_Rest],
		},
		{
			name: 'duneCreditsIncluded',
			type: EntityFieldType.Primitive,
			primitiveType: type('number'),
			cardinality: EntityFieldCardinality.ZeroOrOne,
			defaultSources: [Source.Dune_Rest],
		},
	] as const satisfies readonly EntityFieldDefinition[],
} as const satisfies EntityDefinition
