import { type } from 'arktype'
import {
	EntityFieldCardinality,
	EntityFieldType,
	type EntityDefinition,
} from '$/schema/$schema.ts'
import { EntityType } from '$/schema/EntityType.ts'
export enum A2aAgentCard_SnapshotSelector {
	CardContentHashAlgorithmContentHash = '$card+contentHashAlgorithm+contentHash',
}
export default {
	entityType: EntityType.A2aAgentCard_Snapshot,
	label: 'a2a agent card snapshot',
	labelPlural: 'a2a agent card snapshots',
	selectors: [
		{
			name: A2aAgentCard_SnapshotSelector.CardContentHashAlgorithmContentHash,
			fields: [
				'$card',
				'contentHashAlgorithm',
				'contentHash',
			],
		},
	],
	fields: [
		{
			name: '$card',
			label: 'card',
			type: EntityFieldType.EntityReference,
			entityType: EntityType.A2aAgentCard,
			cardinality: EntityFieldCardinality.One,
		},
		{
			name: 'contentHashAlgorithm',
			label: 'content hash algorithm',
			type: EntityFieldType.Primitive,
			primitiveType: type("string"),
			cardinality: EntityFieldCardinality.One,
		},
		{
			name: 'contentHash',
			label: 'content hash',
			type: EntityFieldType.Primitive,
			primitiveType: type("string"),
			cardinality: EntityFieldCardinality.One,
		},
		{
			name: 'fetchedAt',
			label: 'fetched AT',
			type: EntityFieldType.Primitive,
			primitiveType: type("number"),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: 'snapshotKind',
			label: 'snapshot kind',
			type: EntityFieldType.Primitive,
			primitiveType: type("string"),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: 'name',
			label: 'Name',
			description: 'The human-readable name of the subject.',
			type: EntityFieldType.Primitive,
			primitiveType: type("string"),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: 'description',
			label: 'Description',
			description: 'A human-readable description from the source domain.',
			type: EntityFieldType.Primitive,
			primitiveType: type("string"),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: 'version',
			label: 'version',
			type: EntityFieldType.Primitive,
			primitiveType: type("string"),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: 'protocolVersion',
			label: 'protocol version',
			type: EntityFieldType.Primitive,
			primitiveType: type("string"),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: 'providerName',
			label: 'provider name',
			type: EntityFieldType.Primitive,
			primitiveType: type("string"),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: 'providerUrl',
			label: 'provider URL',
			type: EntityFieldType.Primitive,
			primitiveType: type("string"),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: 'preferredTransport',
			label: 'preferred transport',
			type: EntityFieldType.Primitive,
			primitiveType: type("string"),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: 'defaultInputModes',
			label: 'default input modes',
			type: EntityFieldType.Primitive,
			primitiveType: type("unknown"),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: 'defaultOutputModes',
			label: 'default output modes',
			type: EntityFieldType.Primitive,
			primitiveType: type("unknown"),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: 'capabilities',
			label: 'capabilities',
			type: EntityFieldType.Primitive,
			primitiveType: type("unknown"),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: 'extensions',
			label: 'extensions',
			type: EntityFieldType.Primitive,
			primitiveType: type("unknown"),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: 'securitySchemes',
			label: 'security schemes',
			type: EntityFieldType.Primitive,
			primitiveType: type("unknown"),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: 'security',
			label: 'security',
			type: EntityFieldType.Primitive,
			primitiveType: type("unknown"),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: 'signatures',
			label: 'signatures',
			type: EntityFieldType.Primitive,
			primitiveType: type("unknown"),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: '$$interfaces',
			label: 'interfaces',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.A2aAgentInterface,
			cardinality: EntityFieldCardinality.Many,
		},
		{
			name: '$$services',
			label: 'services',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.A2aAgentService,
			cardinality: EntityFieldCardinality.Many,
		},
		{
			name: '$$skills',
			label: 'skills',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.A2aAgentSkill,
			cardinality: EntityFieldCardinality.Many,
		},
	],
} as const satisfies EntityDefinition
