// Generated from APP.ts. Do not edit by hand.

import { EntityFieldCardinality, EntityFieldType, type EntityDefinition } from '$/schema/$schema.ts'
import { EntityType } from '$/schema/EntityType.ts'
import { UrlString } from '$/schema/UrlString.ts'
import { type } from 'arktype'

export enum AgentPaymentRequirement_TimestampSelector {
	SubjectKindSubjectSelectorPaymentProtocolTimestampMsSource = 'SubjectKindSubjectSelectorPaymentProtocolTimestampMsSource',
}
export default {
	entityType: EntityType.AgentPaymentRequirement_Timestamp,
	label: 'agent payment requirement timestamp',
	labelPlural: 'agent payment requirement observations',
	selectors: [
		{
			name: AgentPaymentRequirement_TimestampSelector.SubjectKindSubjectSelectorPaymentProtocolTimestampMsSource,
			fields: [
				'subjectKind',
				'subjectSelector',
				'paymentProtocol',
				'timestampMs',
				'source',
			],
		},
	],
	fields: [
		{
				name: 'subjectKind',
				label: 'subject kind',
				type: EntityFieldType.Primitive,
				primitiveType: type('string'),
				cardinality: EntityFieldCardinality.One,
		},
		{
				name: 'subjectSelector',
				label: 'subject selector',
				type: EntityFieldType.Primitive,
				primitiveType: type('unknown'),
				cardinality: EntityFieldCardinality.One,
		},
		{
				name: 'paymentProtocol',
				label: 'payment protocol',
				type: EntityFieldType.Primitive,
				primitiveType: type('string'),
				cardinality: EntityFieldCardinality.One,
		},
		{
				name: 'timestampMs',
				label: 'Timestamp',
				description: 'The observation time in Unix milliseconds.',
				type: EntityFieldType.Primitive,
				primitiveType: type('number'),
				cardinality: EntityFieldCardinality.One,
		},
		{
				name: 'source',
				label: 'Source',
				description: 'The source that produced this observation.',
				type: EntityFieldType.Primitive,
				primitiveType: type('string'),
				cardinality: EntityFieldCardinality.One,
		},
		{
				name: '$a2aAgentService',
				label: 'A2A agent service',
				type: EntityFieldType.EntityReference,
				entityType: EntityType.A2aAgentService,
				cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
				name: '$mcpServer',
				label: 'MCP server',
				type: EntityFieldType.EntityReference,
				entityType: EntityType.McpServer,
				cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
				name: '$eip8004ServiceEndpoint',
				label: 'EIP-8004 service endpoint',
				type: EntityFieldType.EntityReference,
				entityType: EntityType.Eip8004AgentServiceEndpoint,
				cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
				name: '$blockheadConnection',
				label: 'blockhead connection',
				type: EntityFieldType.EntityReference,
				entityType: EntityType.BlockheadAgentConnection,
				cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
				name: 'required',
				label: 'required',
				type: EntityFieldType.Primitive,
				primitiveType: type('boolean'),
				cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
				name: 'httpStatus',
				label: 'HTTP status',
				type: EntityFieldType.Primitive,
				primitiveType: type('number'),
				cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
				name: 'requestMethod',
				label: 'request method',
				type: EntityFieldType.Primitive,
				primitiveType: type('string'),
				cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
				name: 'resourceUrl',
				label: 'resource URL',
				type: EntityFieldType.Primitive,
				primitiveType: (UrlString),
				cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
				name: 'paymentRequiredHeader',
				label: 'payment required header',
				type: EntityFieldType.Primitive,
				primitiveType: type('string'),
				cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
				name: 'paymentSignatureHeader',
				label: 'payment signature header',
				type: EntityFieldType.Primitive,
				primitiveType: type('string'),
				cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
				name: 'paymentResponseHeader',
				label: 'payment response header',
				type: EntityFieldType.Primitive,
				primitiveType: type('string'),
				cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
				name: 'paymentRequirements',
				label: 'payment requirements',
				type: EntityFieldType.Primitive,
				primitiveType: type('unknown'),
				cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
				name: 'paymentPayload',
				label: 'payment payload',
				type: EntityFieldType.Primitive,
				primitiveType: type('unknown'),
				cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
				name: 'paymentResponsePayload',
				label: 'payment response payload',
				type: EntityFieldType.Primitive,
				primitiveType: type('unknown'),
				cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
				name: 'facilitatorUrl',
				label: 'facilitator URL',
				type: EntityFieldType.Primitive,
				primitiveType: (UrlString),
				cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
				name: 'scheme',
				label: 'scheme',
				type: EntityFieldType.Primitive,
				primitiveType: type('string'),
				cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
				name: 'assetSelector',
				label: 'asset selector',
				type: EntityFieldType.Primitive,
				primitiveType: type('unknown'),
				cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
				name: 'networkSelector',
				label: 'network selector',
				type: EntityFieldType.Primitive,
				primitiveType: type('unknown'),
				cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
				name: 'price',
				label: 'price',
				type: EntityFieldType.Primitive,
				primitiveType: type('unknown'),
				cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
				name: 'payTo',
				label: 'pay to',
				type: EntityFieldType.Primitive,
				primitiveType: type('unknown'),
				cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
				name: 'maxAmountRequired',
				label: 'max amount required',
				type: EntityFieldType.Primitive,
				primitiveType: type('string'),
				cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
				name: 'maxTimeoutSeconds',
				label: 'max timeout seconds',
				type: EntityFieldType.Primitive,
				primitiveType: type('number'),
				cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
				name: 'evidenceUri',
				label: 'evidence URI',
				type: EntityFieldType.Primitive,
				primitiveType: (UrlString),
				cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
				name: 'error',
				label: 'error',
				type: EntityFieldType.Primitive,
				primitiveType: type('string'),
				cardinality: EntityFieldCardinality.ZeroOrOne,
		},
	],
} as const satisfies EntityDefinition
