// Generated from APP.ts. Do not edit by hand.

import { EntityFieldCardinality, EntityFieldType, type EntityDefinition } from '$/schema/$schema.ts'
import { EntityType } from '$/schema/EntityType.ts'
import { UrlString } from '$/schema/UrlString.ts'
import { type } from 'arktype'

export enum AiEvaluation_TimestampSelector {
	SubjectKindSubjectSelectorBenchmarkMetricNameTimestampMsSource = 'SubjectKindSubjectSelectorBenchmarkMetricNameTimestampMsSource',
}
export default {
	entityType: EntityType.AiEvaluation_Timestamp,
	label: 'AI evaluation timestamp',
	labelPlural: 'AI evaluation observations',
	selectors: [
		{
			name: AiEvaluation_TimestampSelector.SubjectKindSubjectSelectorBenchmarkMetricNameTimestampMsSource,
			fields: [
				'subjectKind',
				'subjectSelector',
				'$benchmark',
				'metricName',
				'timestampMs',
				'source',
			],
		},
	],
	fields: [
		{
			name: 'subjectKind',
			label: 'subject kind',
			type: EntityFieldType.Primitive,
			primitiveType: type('string'),
			cardinality: EntityFieldCardinality.One,
		},
		{
			name: 'subjectSelector',
			label: 'subject selector',
			type: EntityFieldType.Primitive,
			primitiveType: type('unknown'),
			cardinality: EntityFieldCardinality.One,
		},
		{
			name: '$benchmark',
			label: 'benchmark',
			type: EntityFieldType.EntityReference,
			entityType: EntityType.AiBenchmark,
			cardinality: EntityFieldCardinality.One,
		},
		{
			name: 'timestampMs',
			label: 'Timestamp',
			description: 'The observation time in Unix milliseconds.',
			type: EntityFieldType.Primitive,
			primitiveType: type('number'),
			cardinality: EntityFieldCardinality.One,
		},
		{
			name: 'source',
			label: 'Source',
			description: 'The source that produced this observation.',
			type: EntityFieldType.Primitive,
			primitiveType: type('string'),
			cardinality: EntityFieldCardinality.One,
		},
		{
			name: '$model',
			label: 'model',
			type: EntityFieldType.EntityReference,
			entityType: EntityType.AiModel,
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: '$modelVersion',
			label: 'model version',
			type: EntityFieldType.EntityReference,
			entityType: EntityType.AiModelVersion,
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: '$a2aAgentService',
			label: 'a2a agent service',
			type: EntityFieldType.EntityReference,
			entityType: EntityType.A2aAgentService,
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: '$mcpServer',
			label: 'mcp server',
			type: EntityFieldType.EntityReference,
			entityType: EntityType.McpServer,
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: '$eip8004Registration',
			label: 'eip8004 registration',
			type: EntityFieldType.EntityReference,
			entityType: EntityType.Eip8004AgentRegistration,
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: 'sourceRunId',
			label: 'source run ID',
			type: EntityFieldType.Primitive,
			primitiveType: type('string'),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: 'sourceResultId',
			label: 'source result ID',
			type: EntityFieldType.Primitive,
			primitiveType: type('string'),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: 'metricName',
			label: 'metric name',
			type: EntityFieldType.Primitive,
			primitiveType: type('string'),
			cardinality: EntityFieldCardinality.One,
		},
		{
			name: 'metricType',
			label: 'metric type',
			type: EntityFieldType.Primitive,
			primitiveType: type('string'),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: 'value',
			label: 'Value',
			description: 'The source-domain value.',
			type: EntityFieldType.Primitive,
			primitiveType: type('number'),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: 'unit',
			label: 'unit',
			type: EntityFieldType.Primitive,
			primitiveType: type('string'),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: 'step',
			label: 'step',
			type: EntityFieldType.Primitive,
			primitiveType: type('number'),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: 'split',
			label: 'split',
			type: EntityFieldType.Primitive,
			primitiveType: type('string'),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: 'method',
			label: 'method',
			type: EntityFieldType.Primitive,
			primitiveType: type('string'),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: 'harnessVersion',
			label: 'harness version',
			type: EntityFieldType.Primitive,
			primitiveType: type('string'),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: 'datasetName',
			label: 'dataset name',
			type: EntityFieldType.Primitive,
			primitiveType: type('string'),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: 'datasetType',
			label: 'dataset type',
			type: EntityFieldType.Primitive,
			primitiveType: type('string'),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: 'datasetConfig',
			label: 'dataset config',
			type: EntityFieldType.Primitive,
			primitiveType: type('string'),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: 'datasetSplit',
			label: 'dataset split',
			type: EntityFieldType.Primitive,
			primitiveType: type('string'),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: 'datasetDigest',
			label: 'dataset digest',
			type: EntityFieldType.Primitive,
			primitiveType: type('string'),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: 'sourceName',
			label: 'source name',
			type: EntityFieldType.Primitive,
			primitiveType: type('string'),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: 'sourceUrl',
			label: 'source URL',
			type: EntityFieldType.Primitive,
			primitiveType: (UrlString),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: 'payload',
			label: 'payload',
			type: EntityFieldType.Primitive,
			primitiveType: type('unknown'),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
	],
} as const satisfies EntityDefinition
