// Generated from APP.ts. Do not edit by hand.

import { EntityFieldCardinality, EntityFieldType, type EntityDefinition } from '$/schema/$schema.ts'
import { EntityType } from '$/schema/EntityType.ts'
import { ConsensusProtocol } from '$/schema/NetworkUpgradeProtocols.ts'
import { Source } from '$/sources/Source.ts'
import { type } from 'arktype'

export enum EvmNetworkSelector {
	Slug = 'Slug',
	Caip2 = 'Caip2',
}
export default {
	entityType: EntityType.EvmNetwork,
	label: 'EVM network',
	labelPlural: 'EVM networks',
	description: 'An EVM-compatible chain or rollup identified independently of any single RPC provider.',
	selectors: [
		{
			name: EvmNetworkSelector.Slug,
			fields: [
				'slug',
			],
		},
		{
			name: EvmNetworkSelector.Caip2,
			fields: [
				'caip2',
			],
		},
	],
	fields: [
		{
				name: 'slug',
				label: 'Slug',
				type: EntityFieldType.Primitive,
				primitiveType: type('string'),
				cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
				name: 'name',
				label: 'Name',
				type: EntityFieldType.Primitive,
				primitiveType: type('string'),
				cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
				name: 'caip2',
				label: 'CAIP-2',
				type: EntityFieldType.Primitive,
				primitiveType: type({ 'namespace': type.unit('eip155'), 'reference': type('string') }),
				cardinality: EntityFieldCardinality.One,
		},
		{
				name: 'namespace',
				label: 'Namespace',
				type: EntityFieldType.Primitive,
				primitiveType: type('string'),
				cardinality: EntityFieldCardinality.One,
		},
		{
				name: 'environment',
				label: 'Environment',
				type: EntityFieldType.Primitive,
				primitiveType: type('string'),
				cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
				name: 'iconUrl',
				label: 'Icon URL',
				type: EntityFieldType.Primitive,
				primitiveType: type('string'),
				cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
				name: '$icon',
				label: 'Icon',
				type: EntityFieldType.EntityReference,
				entityType: EntityType.Media,
				cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
				name: '$nativeCoin',
				label: 'Native coin',
				type: EntityFieldType.EntityReference,
				entityType: EntityType.Coin,
				cardinality: EntityFieldCardinality.ZeroOrOne,
				defaultSources: [
					Source.Constants_Internal,
				],
		},
		{
				name: '$nativeCoinInstance',
				label: 'Native coin instance',
				type: EntityFieldType.EntityReference,
				entityType: EntityType.EvmCoinInstance,
				cardinality: EntityFieldCardinality.ZeroOrOne,
				defaultSources: [
					Source.Constants_Internal,
				],
		},
		{
				name: 'executionEndpoints',
				label: 'Execution endpoints',
				type: EntityFieldType.Primitive,
				primitiveType: type('string'),
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: 'consensusEndpoints',
				label: 'Consensus endpoints',
				type: EntityFieldType.Primitive,
				primitiveType: type({ 'restBaseUrl': type('string'), 'consensusProtocol': type.enumerated(...Object.values(ConsensusProtocol)) }),
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$rpcUrls',
				label: 'RPC URLs',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.Url,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$blockExplorerUrls',
				label: 'Block explorer URLs',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.Url,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$faucetUrls',
				label: 'Faucet URLs',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.Url,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$nativeAssets',
				label: 'Native assets',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.AssetInstance,
				cardinality: EntityFieldCardinality.Many,
				defaultSources: [
					Source.Constants_Internal,
				],
		},
		{
				name: '$$testnets',
				label: 'Testnets',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.Network,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$childLayers',
				label: 'Child layers',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.Network,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$parent',
				label: 'Parent network',
				type: EntityFieldType.EntityReference,
				entityType: EntityType.Network,
				cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
				name: '$mainnet',
				label: 'Mainnet',
				type: EntityFieldType.EntityReference,
				entityType: EntityType.Network,
				cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
				name: '$$siblingShardNetworks',
				label: 'Sibling shard networks',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.EvmNetwork,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: 'shortName',
				label: 'Short name',
				type: EntityFieldType.Primitive,
				primitiveType: type('string'),
				cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
				name: 'registryStatus',
				label: 'Registry status',
				type: EntityFieldType.Primitive,
				primitiveType: type('string'),
				cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
				name: 'peeringId',
				label: 'Peering ID',
				type: EntityFieldType.Primitive,
				primitiveType: type('number'),
				cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
				name: 'slip44',
				label: 'SLIP-44',
				type: EntityFieldType.Primitive,
				primitiveType: type('number'),
				cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
				name: '$$upgrades',
				label: 'Upgrades',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.EthereumNetworkUpgrade,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$executionUpgrades',
				label: 'Execution upgrades',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.EthereumExecutionUpgrade,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$consensusUpgrades',
				label: 'Consensus upgrades',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.EthereumConsensusUpgrade,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: 'consensusProtocol',
				label: 'Consensus protocol',
				type: EntityFieldType.Primitive,
				primitiveType: type('string'),
				cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
				name: '$$bridges',
				label: 'Bridges',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.EvmNetworkBridge,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$rollup',
				label: 'Rollup',
				type: EntityFieldType.EntityReference,
				entityType: EntityType.EvmRollup,
				cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
				name: '$$settledRollups',
				label: 'Settled rollups',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.EvmRollup,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$timestamps',
				label: 'Timestamps',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.EvmNetwork_Timestamp,
				cardinality: EntityFieldCardinality.ZeroOrMany,
		},
		{
				name: '$$blocks',
				label: 'Blocks',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.EvmBlock,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$transactions',
				label: 'Transactions',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.EvmTransaction,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$contracts',
				label: 'Contracts',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.EvmContract,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$precompiles',
				label: 'Precompiles',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.EvmContract,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$blobs',
				label: 'Blobs',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.EvmBlob,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$gasFeeBlocks',
				label: 'Gas fee blocks',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.EvmNetwork_GasFee_Block,
				cardinality: EntityFieldCardinality.ZeroOrMany,
		},
		{
				name: '$$gasEstimateTimestamps',
				label: 'Gas estimate timestamps',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.EvmNetwork_GasEstimate_Timestamp,
				cardinality: EntityFieldCardinality.ZeroOrMany,
		},
		{
				name: '$$txpoolTimestamps',
				label: 'Txpool timestamps',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.EvmNetwork_Txpool_Timestamp,
				cardinality: EntityFieldCardinality.ZeroOrMany,
		},
		{
				name: '$$erc20TokenTransfers',
				label: 'ERC-20 token transfers',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.EvmTokenTransfer,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$nftTokenTransfers',
				label: 'NFT token transfers',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.EvmTokenTransfer,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$erc4337SmartAccounts',
				label: 'ERC-4337 smart accounts',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.Erc4337SmartAccount,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$erc4337Bundlers',
				label: 'ERC-4337 bundlers',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.Erc4337Bundler,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$erc4337Paymasters',
				label: 'ERC-4337 paymasters',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.Erc4337Paymaster,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$erc4337AccountFactories',
				label: 'ERC-4337 account factories',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.Erc4337AccountFactory,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$userOperations',
				label: 'User operations',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.EvmUserOperation,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$beaconFinalityTimestamps',
				label: 'Beacon finality timestamps',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.EthereumBeaconFinality_Timestamp,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$beaconEpochs',
				label: 'Beacon epochs',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.BeaconEpoch,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$beaconSlots',
				label: 'Beacon slots',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.BeaconSlot,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$beaconCommittees',
				label: 'Beacon committees',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.BeaconCommittee,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$beaconSyncCommittees',
				label: 'Beacon sync committees',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.BeaconSyncCommittee,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$beaconAttestations',
				label: 'Beacon attestations',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.BeaconAttestation,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$beaconWithdrawals',
				label: 'Beacon withdrawals',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.BeaconWithdrawal,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$beaconSlashings',
				label: 'Beacon slashings',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.BeaconSlashing,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$beaconValidators',
				label: 'Beacon validators',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.BeaconValidator,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$mevRelays',
				label: 'MEV relays',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.MevRelay,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$mevBuilders',
				label: 'MEV builders',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.MevBuilder,
				cardinality: EntityFieldCardinality.Many,
		},
		{
				name: '$$mevProposerPayloadDelivered',
				label: 'MEV proposer payloads delivered',
				labelPlural: 'MEV proposer payloads delivered',
				type: EntityFieldType.EntitiesReference,
				entityType: EntityType.MevRelay_ProposerPayloadDelivered,
				cardinality: EntityFieldCardinality.Many,
		},
	],
} as const satisfies EntityDefinition
