import { type } from 'arktype'
import {
	EntityFieldCardinality,
	EntityFieldType,
	type EntityDefinition,
} from '$/schema/$schema.ts'
import { EntityType } from '$/schema/EntityType.ts'
export enum EvmNetworkSelector {
	Caip2 = 'caip2',
}
export default {
	entityType: EntityType.EvmNetwork,
	label: 'EVM network',
	labelPlural: 'EVM networks',
	description: 'An EVM-compatible chain or rollup identified independently of any single RPC provider.',
	selectors: [
		{
			name: EvmNetworkSelector.Caip2,
			fields: [
				'caip2',
			],
		},
	],
	fields: [
		{
			name: 'slug',
			label: 'Slug',
			description: 'A stable short name used by catalogs and URLs.',
			type: EntityFieldType.Primitive,
			primitiveType: type("string"),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: 'name',
			label: 'Name',
			description: 'The human-readable name of the subject.',
			type: EntityFieldType.Primitive,
			primitiveType: type("string"),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: 'caip2',
			label: 'CAIP-2',
			description: 'The chain identifier in CAIP-2 namespace and reference form.',
			type: EntityFieldType.Primitive,
			primitiveType: type({"namespace": "'eip155'", "reference": "string"}),
			cardinality: EntityFieldCardinality.One,
		},
		{
			name: 'namespace',
			label: 'Namespace',
			description: 'The namespace that qualifies the identifier.',
			type: EntityFieldType.Primitive,
			primitiveType: type("'Evm'"),
			cardinality: EntityFieldCardinality.One,
		},
		{
			name: 'environment',
			label: 'environment',
			type: EntityFieldType.Primitive,
			primitiveType: type("string"),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: 'iconUrl',
			label: 'icon URL',
			type: EntityFieldType.Primitive,
			primitiveType: type("string"),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: '$icon',
			label: 'icon',
			type: EntityFieldType.EntityReference,
			entityType: EntityType.Media,
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: '$nativeCoin',
			label: 'native coin',
			type: EntityFieldType.EntityReference,
			entityType: EntityType.Coin,
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: '$nativeCoinInstance',
			label: 'native coin instance',
			type: EntityFieldType.EntityReference,
			entityType: EntityType.EvmCoinInstance,
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: 'executionEndpoints',
			label: 'execution endpoints',
			type: EntityFieldType.Primitive,
			primitiveType: type({"url": "string", "serviceProvider": "string", "transportType": "string"}),
			cardinality: EntityFieldCardinality.Many,
		},
		{
			name: 'consensusEndpoints',
			label: 'consensus endpoints',
			type: EntityFieldType.Primitive,
			primitiveType: type({"restBaseUrl": "string", "consensusProtocol": "string"}),
			cardinality: EntityFieldCardinality.Many,
		},
		{
			name: '$$rpcUrls',
			label: 'RPC urls',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.Url,
			cardinality: EntityFieldCardinality.Many,
		},
		{
			name: '$$blockExplorerUrls',
			label: 'block explorer urls',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.Url,
			cardinality: EntityFieldCardinality.Many,
		},
		{
			name: '$$faucetUrls',
			label: 'faucet urls',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.Url,
			cardinality: EntityFieldCardinality.Many,
		},
		{
			name: '$$nativeAssets',
			label: 'native assets',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.AssetInstance,
			cardinality: EntityFieldCardinality.Many,
		},
		{
			name: '$$testnets',
			label: 'testnets',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.Network,
			cardinality: EntityFieldCardinality.Many,
		},
		{
			name: '$parent',
			label: 'parent',
			type: EntityFieldType.EntityReference,
			entityType: EntityType.Network,
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: '$mainnet',
			label: 'mainnet',
			type: EntityFieldType.EntityReference,
			entityType: EntityType.Network,
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: '$$siblingShardNetworks',
			label: 'sibling shard networks',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.EvmNetwork,
			cardinality: EntityFieldCardinality.Many,
		},
		{
			name: 'shortName',
			label: 'short name',
			type: EntityFieldType.Primitive,
			primitiveType: type("string"),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: 'registryStatus',
			label: 'registry status',
			type: EntityFieldType.Primitive,
			primitiveType: type("string"),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: 'peeringId',
			label: 'peering ID',
			type: EntityFieldType.Primitive,
			primitiveType: type("number"),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: 'slip44',
			label: 'slip44',
			type: EntityFieldType.Primitive,
			primitiveType: type("number"),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: '$$upgrades',
			label: 'upgrades',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.EthereumNetworkUpgrade,
			cardinality: EntityFieldCardinality.Many,
		},
		{
			name: '$$executionUpgrades',
			label: 'execution upgrades',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.EthereumExecutionUpgrade,
			cardinality: EntityFieldCardinality.Many,
		},
		{
			name: '$$consensusUpgrades',
			label: 'consensus upgrades',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.EthereumConsensusUpgrade,
			cardinality: EntityFieldCardinality.Many,
		},
		{
			name: 'consensusProtocol',
			label: 'consensus protocol',
			type: EntityFieldType.Primitive,
			primitiveType: type("string"),
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: '$$bridges',
			label: 'bridges',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.EvmNetworkBridge,
			cardinality: EntityFieldCardinality.Many,
		},
		{
			name: '$rollup',
			label: 'rollup',
			type: EntityFieldType.EntityReference,
			entityType: EntityType.EvmRollup,
			cardinality: EntityFieldCardinality.ZeroOrOne,
		},
		{
			name: '$$settledRollups',
			label: 'settled rollups',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.EvmRollup,
			cardinality: EntityFieldCardinality.Many,
		},
		{
			name: '$$timestamps',
			label: 'timestamps',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.EvmNetwork_Timestamp,
			cardinality: EntityFieldCardinality.ZeroOrMany,
		},
		{
			name: '$$blocks',
			label: 'blocks',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.EvmBlock,
			cardinality: EntityFieldCardinality.Many,
		},
		{
			name: '$$transactions',
			label: 'transactions',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.EvmTransaction,
			cardinality: EntityFieldCardinality.Many,
		},
		{
			name: '$$contracts',
			label: 'contracts',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.EvmContract,
			cardinality: EntityFieldCardinality.Many,
		},
		{
			name: '$$precompiles',
			label: 'precompiles',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.EvmContract,
			cardinality: EntityFieldCardinality.Many,
		},
		{
			name: '$$blobs',
			label: 'blobs',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.EvmBlob,
			cardinality: EntityFieldCardinality.Many,
		},
		{
			name: '$$gasFeeBlocks',
			label: 'gas fee blocks',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.EvmNetwork_GasFee_Block,
			cardinality: EntityFieldCardinality.ZeroOrMany,
		},
		{
			name: '$$gasEstimateTimestamps',
			label: 'gas estimate timestamps',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.EvmNetwork_GasEstimate_Timestamp,
			cardinality: EntityFieldCardinality.ZeroOrMany,
		},
		{
			name: '$$txpoolTimestamps',
			label: 'txpool timestamps',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.EvmNetwork_Txpool_Timestamp,
			cardinality: EntityFieldCardinality.ZeroOrMany,
		},
		{
			name: '$$erc20TokenTransfers',
			label: 'erc20 token transfers',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.EvmTokenTransfer,
			cardinality: EntityFieldCardinality.Many,
		},
		{
			name: '$$nftTokenTransfers',
			label: 'NFT token transfers',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.EvmTokenTransfer,
			cardinality: EntityFieldCardinality.Many,
		},
		{
			name: '$$erc4337SmartAccounts',
			label: 'erc4337 smart accounts',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.Erc4337SmartAccount,
			cardinality: EntityFieldCardinality.Many,
		},
		{
			name: '$$erc4337Bundlers',
			label: 'erc4337 bundlers',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.Erc4337Bundler,
			cardinality: EntityFieldCardinality.Many,
		},
		{
			name: '$$erc4337Paymasters',
			label: 'erc4337 paymasters',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.Erc4337Paymaster,
			cardinality: EntityFieldCardinality.Many,
		},
		{
			name: '$$erc4337AccountFactories',
			label: 'erc4337 account factories',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.Erc4337AccountFactory,
			cardinality: EntityFieldCardinality.Many,
		},
		{
			name: '$$userOperations',
			label: 'user operations',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.EvmUserOperation,
			cardinality: EntityFieldCardinality.Many,
		},
		{
			name: '$$beaconFinalityTimestamps',
			label: 'beacon finality timestamps',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.EthereumBeaconFinality_Timestamp,
			cardinality: EntityFieldCardinality.Many,
		},
		{
			name: '$$beaconEpochs',
			label: 'beacon epochs',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.BeaconEpoch,
			cardinality: EntityFieldCardinality.Many,
		},
		{
			name: '$$beaconSlots',
			label: 'beacon slots',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.BeaconSlot,
			cardinality: EntityFieldCardinality.Many,
		},
		{
			name: '$$beaconCommittees',
			label: 'beacon committees',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.BeaconCommittee,
			cardinality: EntityFieldCardinality.Many,
		},
		{
			name: '$$beaconSyncCommittees',
			label: 'beacon sync committees',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.BeaconSyncCommittee,
			cardinality: EntityFieldCardinality.Many,
		},
		{
			name: '$$beaconAttestations',
			label: 'beacon attestations',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.BeaconAttestation,
			cardinality: EntityFieldCardinality.Many,
		},
		{
			name: '$$beaconWithdrawals',
			label: 'beacon withdrawals',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.BeaconWithdrawal,
			cardinality: EntityFieldCardinality.Many,
		},
		{
			name: '$$beaconSlashings',
			label: 'beacon slashings',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.BeaconSlashing,
			cardinality: EntityFieldCardinality.Many,
		},
		{
			name: '$$beaconValidators',
			label: 'beacon validators',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.BeaconValidator,
			cardinality: EntityFieldCardinality.Many,
		},
		{
			name: '$$mevRelays',
			label: 'mev relays',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.MevRelay,
			cardinality: EntityFieldCardinality.Many,
		},
		{
			name: '$$mevBuilders',
			label: 'mev builders',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.MevBuilder,
			cardinality: EntityFieldCardinality.Many,
		},
		{
			name: '$$mevProposerPayloadDelivered',
			label: 'mev proposer payload delivered',
			labelPlural: 'mev proposer payload deliveredses',
			type: EntityFieldType.EntitiesReference,
			entityType: EntityType.MevRelay_ProposerPayloadDelivered,
			cardinality: EntityFieldCardinality.Many,
		},
	],
} as const satisfies EntityDefinition
